"""The Embodied Operation Harness: one supervised laboratory instrument loop.

This package is original. It does not inherit the discovery harness's complaint
routing, candidate search, objective scoring, or MAS workflow, and nothing in it
treats a physical operation as an experiment to be searched.

It is organised around a single physical claim: on this embodiment the whole-body
tracker is not an executor bolted onto a stable machine, it *is* what keeps a
standing biped upright. Every seam here follows from that.

``target``    the only frame a policy may publish, validated at construction
``tracker``   the vendored TWIST2 transport, and the dead-man inside its loop
``bridge``    the sole path to the actuators: authority, ordering, freshness
``witness``   the lid bit, from a channel the policy cannot see
``monitor``   the veto on the one irreversible act; it can only hold
``episode``   what one run leaves behind, and what it may prove
``policy``    the serving shape: a slow intent, a fast target, one clock
``session``   the composition -- the only thing that runs a loop end to end

Read them in that order. Each one refuses something the next one would otherwise
have to trust.

Three more modules sit outside that spine, because they are not on the path a
frame takes to the robot:

``dataset``   recorded episodes become samples, and every shortfall is named
``vision``    recorded views become features, with the crop carried in the reference
``learn``     samples become a servable policy that cannot overstate itself
``deploy``    the one seam that must change code we do not own

``learn`` and ``vision`` import torch lazily. The actuation path does not need it, and the
machine that only runs the actuation path is the machine that matters most.

Above the spine sits the experiment loop layer -- the system that owns "next
episode", "next batch" and "next generation", built for the reversible
no-liquid task (a "pour" is a visible tilt gesture only):

``trace``     the whole witnessed operation trace, and its pure adjudication
``campaign``  the append-only ledger: generations, plans, predictions,
              results, envelopes, work orders
``predict``   the imagined bench, and the calibration its authority costs
``design``    the next batch, stated and pre-registered before it runs
``loop``      the composition above the session: batches that turn

It reuses the spine through an executor boundary and never reaches around it:
no joint, tick, or target is owned above ``session``.
"""

from __future__ import annotations

from vegapunk.operation.bridge import (
    ACCEPTED,
    REFUSED_LATCHED,
    REFUSED_NO_AUTHORITY,
    REFUSED_OUT_OF_ORDER,
    REFUSED_STALE,
    MotionGrant,
    PublishResult,
    TargetBridge,
)
from vegapunk.operation.campaign import (
    EXECUTION_COMPLETED,
    EXECUTION_FAULT,
    EXECUTION_HELD,
    SOURCE_PREDICTED,
    SOURCE_REAL,
    STOP_AWAITING_HUMAN,
    STOP_CIRCUIT_BREAKER,
    STOP_COMPLETED,
    BatchPlan,
    BatchResult,
    BenchConfiguration,
    CalibrationScore,
    Campaign,
    Condition,
    EffectivenessReport,
    EnvelopeCell,
    EpisodeEvidence,
    Generation,
    GenerationSeal,
    Prediction,
    ReliabilityEnvelope,
    WorkOrder,
    WorkOrderConfirmation,
)
from vegapunk.operation.dataset import (
    ALIGNED_BY_CLOCK,
    ALIGNED_BY_INDEX,
    ConversionReport,
    TrainingSample,
    VendoredEpisode,
    convert_episode,
    convert_vendored_tree,
)
from vegapunk.operation.deploy import (
    PATCH_ANCHOR,
    TrackerLoopAdapter,
)
from vegapunk.operation.design import (
    CLASS_CONDITION,
    CLASS_DATA,
    CLASS_ENVIRONMENT,
    CLASS_INVOCATION,
    PROPOSAL_CLASSES,
    BatchDesign,
    Proposal,
    RefusedCondition,
    TableBatchDesigner,
)
from vegapunk.operation.episode import (
    EVENTS_FILE,
    FRAMES_FILE,
    MANIFEST_FILE,
    TERMINATION_COMPLETED,
    TERMINATION_FAULT,
    TERMINATION_HELD,
    TERMINATION_OPERATOR_STOP,
    TRANSFER_FULL,
    TRANSFER_NONE,
    TRANSFER_PARTIAL,
    CameraCalibration,
    EpisodeOutcome,
    EpisodeRecord,
    EpisodeWriter,
    Frame,
    HumanTestimony,
    ResetRecord,
    SafetyEvent,
)
from vegapunk.operation.learn import (
    ACTION_DIM,
    CHECKPOINT_FILE,
    PROJECTION_ALARM_RAD,
    STATE_DIM,
    ChunkDataset,
    ImageEncoder,
    LearnedFastPolicy,
    Normalizer,
    TrainingConfig,
    TrainingResult,
    build_network,
    save_checkpoint,
    train,
)
from vegapunk.operation.loop import (
    CircuitBreaker,
    EpisodeExecutor,
    EpisodeRun,
    ExperimentLoop,
    SessionEpisode,
    SessionEpisodeExecutor,
)
from vegapunk.operation.monitor import (
    HOLD_LID_NOT_OPEN,
    PASS,
    InstrumentMonitor,
    MonitorVerdict,
    PourPosture,
)
from vegapunk.operation.policy import (
    DEFAULT_CHUNK_PERIODS,
    DEFAULT_INTENT_MAX_AGE_S,
    ActionChunk,
    FastPolicy,
    IntentProducer,
    Observation,
    PolicyServer,
    ReplayFastPolicy,
    SlowIntent,
)
from vegapunk.operation.predict import (
    DEFAULT_MIN_ACCURACY,
    DEFAULT_MIN_SCORED,
    CalibrationPolicy,
    Forecast,
    PredictiveNode,
    TabularPredictiveNode,
    score_predictions,
)
from vegapunk.operation.session import (
    COMPLETED,
    HELD,
    HOLD_MONITOR_VETO,
    HOLD_OPERATOR,
    HOLD_REFUSED,
    HOLD_STARVED,
    RUNNING,
    OperationSession,
    TickResult,
)
from vegapunk.operation.target import (
    BODY_DIM,
    CONTROL_HZ,
    CONTROL_PERIOD_S,
    G1_JOINT_LIMITS_RAD,
    G1_JOINT_NAMES,
    HAND_CLOSED,
    HAND_DIM,
    HAND_JOINT_NAMES,
    HAND_LIMITS_RAD,
    HAND_OPEN,
    JOINT_DIM,
    MAX_ROOT_SPEED_MPS,
    MAX_ROOT_YAW_RATE_RPS,
    STAND_BODY,
    WholeBodyTarget,
    safe_hold_target,
)
from vegapunk.operation.trace import (
    FACT_DEFINITE,
    FACT_INDETERMINATE,
    OUTCOME_FAILED,
    OUTCOME_INDETERMINATE,
    OUTCOME_SUCCEEDED,
    PREDICATE_CUP_LIFTED,
    PREDICATE_CUP_RETURNED,
    PREDICATE_CUP_TILTED,
    PREDICATE_FINAL_LID_CLOSED,
    PREDICATE_INITIAL_LID_CLOSED,
    PREDICATE_LID_OPENED,
    REQUIRED_TRACE,
    TRACE_OUTCOMES,
    OperationTraceWitness,
    ResetVerdict,
    ResetWitness,
    TraceAdjudication,
    TraceFact,
    adjudicate,
)
from vegapunk.operation.tracker import (
    LAPSE_ABSENT,
    LAPSE_EXPIRED,
    LAPSE_NONE,
    LAPSE_REGRESSED,
    GuardVerdict,
    RedisTrackerTransport,
    TrackerLoopGuard,
    TrackerState,
    TrackerTransport,
)
from vegapunk.operation.vision import (
    DEFAULT_INPUT_SIZE,
    DEFAULT_RESNET18_CACHE,
    RESNET18_FEATURE_DIM,
    ResNet18Trunk,
    ViewReference,
    VisionEncoder,
    load_view,
)
from vegapunk.operation.witness import (
    LID_CLOSED,
    LID_INDETERMINATE,
    LID_OPEN,
    GeometricWitness,
    IndependentWitness,
    SwitchWitness,
    LidChannel,
    LidReading,
    RegionTest,
    WitnessVerdict,
)

__all__ = [
    "ACCEPTED",
    "ACTION_DIM",
    "ALIGNED_BY_CLOCK",
    "ALIGNED_BY_INDEX",
    "ActionChunk",
    "BODY_DIM",
    "BatchDesign",
    "BatchPlan",
    "BatchResult",
    "BenchConfiguration",
    "CHECKPOINT_FILE",
    "CLASS_CONDITION",
    "CLASS_DATA",
    "CLASS_ENVIRONMENT",
    "CLASS_INVOCATION",
    "COMPLETED",
    "CONTROL_HZ",
    "CONTROL_PERIOD_S",
    "CalibrationPolicy",
    "CalibrationScore",
    "Campaign",
    "CameraCalibration",
    "ChunkDataset",
    "CircuitBreaker",
    "Condition",
    "ConversionReport",
    "DEFAULT_CHUNK_PERIODS",
    "DEFAULT_INTENT_MAX_AGE_S",
    "DEFAULT_MIN_ACCURACY",
    "DEFAULT_MIN_SCORED",
    "EVENTS_FILE",
    "EXECUTION_COMPLETED",
    "EXECUTION_FAULT",
    "EXECUTION_HELD",
    "EffectivenessReport",
    "EnvelopeCell",
    "EpisodeEvidence",
    "EpisodeExecutor",
    "EpisodeOutcome",
    "EpisodeRecord",
    "EpisodeRun",
    "EpisodeWriter",
    "ExperimentLoop",
    "FACT_DEFINITE",
    "FACT_INDETERMINATE",
    "FRAMES_FILE",
    "FastPolicy",
    "Forecast",
    "Frame",
    "G1_JOINT_LIMITS_RAD",
    "G1_JOINT_NAMES",
    "Generation",
    "GenerationSeal",
    "GeometricWitness",
    "GuardVerdict",
    "HAND_CLOSED",
    "HAND_DIM",
    "HAND_JOINT_NAMES",
    "HAND_LIMITS_RAD",
    "HAND_OPEN",
    "HELD",
    "HOLD_LID_NOT_OPEN",
    "HOLD_MONITOR_VETO",
    "HOLD_OPERATOR",
    "HOLD_REFUSED",
    "HOLD_STARVED",
    "HumanTestimony",
    "ImageEncoder",
    "IndependentWitness",
    "InstrumentMonitor",
    "SwitchWitness",
    "IntentProducer",
    "JOINT_DIM",
    "LAPSE_ABSENT",
    "LAPSE_EXPIRED",
    "LAPSE_NONE",
    "LAPSE_REGRESSED",
    "LID_CLOSED",
    "LID_INDETERMINATE",
    "LID_OPEN",
    "LearnedFastPolicy",
    "LidChannel",
    "LidReading",
    "MANIFEST_FILE",
    "MAX_ROOT_SPEED_MPS",
    "MAX_ROOT_YAW_RATE_RPS",
    "MonitorVerdict",
    "MotionGrant",
    "Normalizer",
    "OUTCOME_FAILED",
    "OUTCOME_INDETERMINATE",
    "OUTCOME_SUCCEEDED",
    "Observation",
    "OperationSession",
    "OperationTraceWitness",
    "PASS",
    "PATCH_ANCHOR",
    "PREDICATE_CUP_LIFTED",
    "PREDICATE_CUP_RETURNED",
    "PREDICATE_CUP_TILTED",
    "PREDICATE_FINAL_LID_CLOSED",
    "PREDICATE_INITIAL_LID_CLOSED",
    "PREDICATE_LID_OPENED",
    "PROJECTION_ALARM_RAD",
    "PROPOSAL_CLASSES",
    "PolicyServer",
    "PourPosture",
    "Prediction",
    "PredictiveNode",
    "Proposal",
    "PublishResult",
    "REFUSED_LATCHED",
    "REFUSED_NO_AUTHORITY",
    "REFUSED_OUT_OF_ORDER",
    "REFUSED_STALE",
    "REQUIRED_TRACE",
    "RUNNING",
    "RedisTrackerTransport",
    "RefusedCondition",
    "RegionTest",
    "ReliabilityEnvelope",
    "ReplayFastPolicy",
    "ResetRecord",
    "ResetVerdict",
    "ResetWitness",
    "SOURCE_PREDICTED",
    "SOURCE_REAL",
    "STAND_BODY",
    "STATE_DIM",
    "STOP_AWAITING_HUMAN",
    "STOP_CIRCUIT_BREAKER",
    "STOP_COMPLETED",
    "SafetyEvent",
    "SessionEpisode",
    "SessionEpisodeExecutor",
    "SlowIntent",
    "TERMINATION_COMPLETED",
    "TERMINATION_FAULT",
    "TERMINATION_HELD",
    "TERMINATION_OPERATOR_STOP",
    "TRACE_OUTCOMES",
    "TRANSFER_FULL",
    "TRANSFER_NONE",
    "TRANSFER_PARTIAL",
    "TableBatchDesigner",
    "TabularPredictiveNode",
    "TargetBridge",
    "TickResult",
    "TraceAdjudication",
    "TraceFact",
    "TrackerLoopAdapter",
    "TrackerLoopGuard",
    "TrackerState",
    "TrackerTransport",
    "TrainingConfig",
    "TrainingResult",
    "TrainingSample",
    "VendoredEpisode",
    "WorkOrder",
    "WorkOrderConfirmation",
    "DEFAULT_INPUT_SIZE",
    "DEFAULT_RESNET18_CACHE",
    "RESNET18_FEATURE_DIM",
    "ResNet18Trunk",
    "ViewReference",
    "VisionEncoder",
    "load_view",
    "WholeBodyTarget",
    "WitnessVerdict",
    "adjudicate",
    "build_network",
    "convert_episode",
    "convert_vendored_tree",
    "safe_hold_target",
    "save_checkpoint",
    "score_predictions",
    "train",
]
