use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::fs;
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};
use std::sync::Mutex;

use rusqlite::Connection;
use tauri::{AppHandle, Emitter};

use crate::services::config_manager::ConfigManager;

const USAGE_DB_FILE: &str = "usage.db";
const PENDING_DIR: &str = "usage-pending";
const HOOK_DIR: &str = "hooks";
const HOOK_SCRIPT_NAME_UNIX: &str = "claude-skill-usage.sh";
const HOOK_SCRIPT_NAME_WIN: &str = "claude-skill-usage.ps1";
const HOOK_MARKER: &str = "# skills-manager-usage-hook";
const LEGACY_LOG_FILE: &str = "usage-events.logl";

// Codex hook constants
const CODEX_HOOK_SCRIPT_NAME_UNIX: &str = "codex-skill-usage.sh";
const CODEX_HOOK_SCRIPT_NAME_WIN: &str = "codex-skill-usage.ps1";
const CODEX_HOOK_MARKER: &str = "# skills-manager-codex-usage-hook";
const TRANSCRIPT_TAIL_BYTES: u64 = 2 * 1024 * 1024;

// WorkBuddy hook constants
const WORKBUDDY_HOOK_SCRIPT_NAME_UNIX: &str = "workbuddy-skill-usage.sh";
const WORKBUDDY_HOOK_SCRIPT_NAME_WIN: &str = "workbuddy-skill-usage.ps1";
const WORKBUDDY_PLUGIN_ID: &str = "skills-manager-usage";
const WORKBUDDY_MARKETPLACE_ID: &str = "skills-manager-local";

/// Bash 版 hook 脚本（macOS/Linux）
/// 每次调用生成独立文件，避免并发写入冲突
const HOOK_SCRIPT_UNIX: &str = r#"#!/bin/bash
# skills-manager-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Zero external dependencies: only bash + sed + tr (no jq required).
# Writes one file per event to avoid concurrent write conflicts.
input=$(cat)
[ -z "$input" ] && exit 0
ts=$(date +%s)
pid=$$
rand=$RANDOM
dir="$HOME/.skills-manager/usage-pending"
mkdir -p "$dir" 2>/dev/null
# Escape for JSON string embedding, collapse newlines
escaped=$(printf '%s' "$input" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' ')
tmp="${dir}/.tmp-${ts}-${pid}-${rand}"
final="${dir}/${ts}-${pid}-${rand}.json"
echo "{\"raw\":\"$escaped\",\"tool_id\":\"claude-code\",\"ts\":$ts}" > "$tmp"
mv "$tmp" "$final"
"#;

/// PowerShell 版 hook 脚本（Windows）
const HOOK_SCRIPT_WIN: &str = r#"# skills-manager-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Writes one file per event to avoid concurrent write conflicts.
$input = [Console]::In.ReadToEnd()
if ([string]::IsNullOrEmpty($input)) { exit 0 }
$ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$procId = $PID
$rand = Get-Random -Maximum 999999
$dir = Join-Path $env:USERPROFILE ".skills-manager\usage-pending"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$escaped = $input -replace '\\', '\\' -replace '"', '\"' -replace "`r?`n", " "
$content = "{`"raw`":`"$escaped`",`"tool_id`":`"claude-code`",`"ts`":$ts}"
$final = Join-Path $dir "${ts}-${procId}-${rand}.json"
$tmp = Join-Path $dir ".tmp-${ts}-${procId}-${rand}"
[System.IO.File]::WriteAllText($tmp, $content)
Rename-Item -Path $tmp -Destination $final
"#;

/// Codex Bash 版 hook 脚本（macOS/Linux）
/// 与 Claude Code 版相同逻辑，但 tool_id 为 "codex"
const CODEX_HOOK_SCRIPT_UNIX: &str = r#"#!/bin/bash
# skills-manager-codex-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Zero external dependencies: only bash + sed + tr (no jq required).
# Writes one file per event to avoid concurrent write conflicts.
input=$(cat)
[ -z "$input" ] && exit 0
ts=$(date +%s)
pid=$$
rand=$RANDOM
dir="$HOME/.skills-manager/usage-pending"
mkdir -p "$dir" 2>/dev/null
# Escape for JSON string embedding, collapse newlines
escaped=$(printf '%s' "$input" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' ')
tmp="${dir}/.tmp-${ts}-${pid}-${rand}"
final="${dir}/${ts}-${pid}-${rand}.json"
echo "{\"raw\":\"$escaped\",\"tool_id\":\"codex\",\"ts\":$ts}" > "$tmp"
mv "$tmp" "$final"
"#;

/// Codex PowerShell 版 hook 脚本（Windows）
const CODEX_HOOK_SCRIPT_WIN: &str = r#"# skills-manager-codex-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Writes one file per event to avoid concurrent write conflicts.
$input = [Console]::In.ReadToEnd()
if ([string]::IsNullOrEmpty($input)) { exit 0 }
$ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$procId = $PID
$rand = Get-Random -Maximum 999999
$dir = Join-Path $env:USERPROFILE ".skills-manager\usage-pending"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$escaped = $input -replace '\\', '\\' -replace '"', '\"' -replace "`r?`n", " "
$content = "{`"raw`":`"$escaped`",`"tool_id`":`"codex`",`"ts`":$ts}"
$final = Join-Path $dir "${ts}-${procId}-${rand}.json"
$tmp = Join-Path $dir ".tmp-${ts}-${procId}-${rand}"
[System.IO.File]::WriteAllText($tmp, $content)
Rename-Item -Path $tmp -Destination $final
"#;

/// WorkBuddy Bash 版 hook 脚本（macOS/Linux）
/// 与 Claude Code 版相同逻辑，但 tool_id 为 "workbuddy"
const WORKBUDDY_HOOK_SCRIPT_UNIX: &str = r#"#!/bin/bash
# skills-manager-workbuddy-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Zero external dependencies: only bash + sed + tr (no jq required).
# Writes one file per event to avoid concurrent write conflicts.
input=$(cat)
[ -z "$input" ] && exit 0
ts=$(date +%s)
pid=$$
rand=$RANDOM
dir="$HOME/.skills-manager/usage-pending"
mkdir -p "$dir" 2>/dev/null
# Escape for JSON string embedding, collapse newlines
escaped=$(printf '%s' "$input" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' ')
tmp="${dir}/.tmp-${ts}-${pid}-${rand}"
final="${dir}/${ts}-${pid}-${rand}.json"
echo "{\"raw\":\"$escaped\",\"tool_id\":\"workbuddy\",\"ts\":$ts}" > "$tmp"
mv "$tmp" "$final"
"#;

/// WorkBuddy PowerShell 版 hook 脚本（Windows）
const WORKBUDDY_HOOK_SCRIPT_WIN: &str = r#"# skills-manager-workbuddy-usage-hook
# Auto-generated by Skills Manager. Do not edit manually.
# Writes one file per event to avoid concurrent write conflicts.
$input = [Console]::In.ReadToEnd()
if ([string]::IsNullOrEmpty($input)) { exit 0 }
$ts = [DateTimeOffset]::UtcNow.ToUnixTimeSeconds()
$procId = $PID
$rand = Get-Random -Maximum 999999
$dir = Join-Path $env:USERPROFILE ".skills-manager\usage-pending"
New-Item -ItemType Directory -Force -Path $dir | Out-Null
$escaped = $input -replace '\\', '\\' -replace '"', '\"' -replace "`r?`n", " "
$content = "{`"raw`":`"$escaped`",`"tool_id`":`"workbuddy`",`"ts`":$ts}"
$final = Join-Path $dir "${ts}-${procId}-${rand}.json"
$tmp = Join-Path $dir ".tmp-${ts}-${procId}-${rand}"
[System.IO.File]::WriteAllText($tmp, $content)
Rename-Item -Path $tmp -Destination $final
"#;

#[derive(Debug, Deserialize)]
struct UsageEvent {
    raw: Option<String>,
    tool_id: String,
    ts: i64,
}

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct SkillUsageStats {
    pub total: u64,
    pub by_tool: HashMap<String, u64>,
    pub last_called_at: Option<i64>,
}

fn skills_manager_dir() -> PathBuf {
    dirs::home_dir().unwrap_or_default().join(".skills-manager")
}

fn usage_db_path() -> PathBuf {
    skills_manager_dir().join(USAGE_DB_FILE)
}

fn pending_dir() -> PathBuf {
    skills_manager_dir().join(PENDING_DIR)
}

fn hook_script_path() -> PathBuf {
    let name = if cfg!(target_os = "windows") {
        HOOK_SCRIPT_NAME_WIN
    } else {
        HOOK_SCRIPT_NAME_UNIX
    };
    skills_manager_dir().join(HOOK_DIR).join(name)
}

fn hook_script_content() -> &'static str {
    if cfg!(target_os = "windows") {
        HOOK_SCRIPT_WIN
    } else {
        HOOK_SCRIPT_UNIX
    }
}

// ===== Codex hook path helpers =====

fn codex_hooks_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".codex")
        .join("hooks.json")
}

fn codex_hook_script_path() -> PathBuf {
    let name = if cfg!(target_os = "windows") {
        CODEX_HOOK_SCRIPT_NAME_WIN
    } else {
        CODEX_HOOK_SCRIPT_NAME_UNIX
    };
    skills_manager_dir().join(HOOK_DIR).join(name)
}

fn codex_hook_script_content() -> &'static str {
    if cfg!(target_os = "windows") {
        CODEX_HOOK_SCRIPT_WIN
    } else {
        CODEX_HOOK_SCRIPT_UNIX
    }
}

fn build_codex_hook_command() -> String {
    let script_path = codex_hook_script_path();
    if cfg!(target_os = "windows") {
        format!(
            "powershell -ExecutionPolicy Bypass -File \"{}\"",
            script_path.to_string_lossy()
        )
    } else {
        format!("bash \"{}\"", script_path.to_string_lossy())
    }
}

// ===== WorkBuddy hook path helpers =====

fn workbuddy_settings_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".workbuddy")
        .join("settings.json")
}

fn workbuddy_known_marketplaces_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".workbuddy")
        .join("plugins")
        .join("known_marketplaces.json")
}

/// WorkBuddy marketplace 根目录: ~/.skills-manager/hooks/workbuddy-plugin/
/// 该目录本身是一个 directory 类型的 marketplace，包含一个 skills-manager-usage 插件
fn workbuddy_plugin_root() -> PathBuf {
    skills_manager_dir().join(HOOK_DIR).join("workbuddy-plugin")
}

/// WorkBuddy 插件安装目录: <marketplace_root>/skills-manager-usage/
fn workbuddy_plugin_install_dir() -> PathBuf {
    workbuddy_plugin_root().join("skills-manager-usage")
}

fn workbuddy_hook_script_path() -> PathBuf {
    let name = if cfg!(target_os = "windows") {
        WORKBUDDY_HOOK_SCRIPT_NAME_WIN
    } else {
        WORKBUDDY_HOOK_SCRIPT_NAME_UNIX
    };
    workbuddy_plugin_install_dir().join("hooks").join(name)
}

fn workbuddy_hook_script_content() -> &'static str {
    if cfg!(target_os = "windows") {
        WORKBUDDY_HOOK_SCRIPT_WIN
    } else {
        WORKBUDDY_HOOK_SCRIPT_UNIX
    }
}

fn build_workbuddy_hook_command() -> String {
    let script_path = workbuddy_hook_script_path();
    if cfg!(target_os = "windows") {
        format!(
            "powershell -ExecutionPolicy Bypass -File \"{}\"",
            script_path.to_string_lossy()
        )
    } else {
        format!("bash \"{}\"", script_path.to_string_lossy())
    }
}

/// 建立数据库连接并初始化表
fn open_db() -> Result<Connection, String> {
    let db_path = usage_db_path();
    if let Some(parent) = db_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create db dir: {}", e))?;
    }
    let conn = Connection::open(&db_path).map_err(|e| format!("Failed to open usage db: {}", e))?;
    conn.execute_batch(
        "CREATE TABLE IF NOT EXISTS usage_events (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            skill_id TEXT NOT NULL,
            tool_id TEXT NOT NULL,
            event_type TEXT NOT NULL,
            ts INTEGER NOT NULL
        );
        CREATE INDEX IF NOT EXISTS idx_usage_skill ON usage_events(skill_id);
        CREATE INDEX IF NOT EXISTS idx_usage_tool ON usage_events(tool_id);
        CREATE INDEX IF NOT EXISTS idx_usage_ts ON usage_events(ts);",
    )
    .map_err(|e| format!("Failed to init usage table: {}", e))?;

    ensure_usage_column(&conn, "session_id", "TEXT")?;
    ensure_usage_column(&conn, "turn_id", "TEXT")?;
    ensure_usage_column(&conn, "source", "TEXT")?;
    ensure_usage_column(&conn, "dedupe_key", "TEXT")?;
    conn.execute_batch(
        "CREATE UNIQUE INDEX IF NOT EXISTS idx_usage_dedupe
         ON usage_events(dedupe_key)
         WHERE dedupe_key IS NOT NULL;",
    )
    .map_err(|e| format!("Failed to init usage dedupe index: {}", e))?;
    Ok(conn)
}

fn ensure_usage_column(conn: &Connection, name: &str, column_type: &str) -> Result<(), String> {
    let mut stmt = conn
        .prepare("PRAGMA table_info(usage_events)")
        .map_err(|e| format!("Failed to inspect usage table: {}", e))?;
    let columns = stmt
        .query_map([], |row| row.get::<_, String>(1))
        .map_err(|e| format!("Failed to query usage columns: {}", e))?;
    if columns.flatten().any(|column| column == name) {
        return Ok(());
    }
    conn.execute(
        &format!(
            "ALTER TABLE usage_events ADD COLUMN {} {}",
            name, column_type
        ),
        [],
    )
    .map_err(|e| format!("Failed to add usage column {}: {}", name, e))?;
    Ok(())
}

#[derive(Debug)]
struct ExtractedUsage {
    skill_ids: Vec<String>,
    session_id: Option<String>,
    turn_id: Option<String>,
    event_type: String,
    source: &'static str,
}

/// Extract skill identifiers and turn metadata from a hook event.
fn extract_usage(event: &UsageEvent) -> Option<ExtractedUsage> {
    let raw = event.raw.as_ref()?;
    let raw_value: serde_json::Value = serde_json::from_str(raw).ok()?;
    let hook_event = raw_value.get("hook_event_name").and_then(|v| v.as_str())?;
    let session_id = raw_value
        .get("session_id")
        .and_then(|v| v.as_str())
        .map(str::to_string);
    let turn_id = raw_value
        .get("turn_id")
        .and_then(|v| v.as_str())
        .map(str::to_string);

    let (skill_ids, source) = match hook_event {
        "PostToolUse" => {
            let tool_input = raw_value.get("tool_input")?;
            let ids = if event.tool_id == "codex" {
                // Codex does not expose a Skill tool. Generic MCP inputs may
                // contain fields such as `name`, so only count actual SKILL.md
                // paths for Codex instead of interpreting arbitrary fields.
                extract_skill_ids_from_skill_paths(tool_input)
            } else {
                extract_skill_ids_from_value(tool_input)
            };
            (ids, "post_tool_use")
        }
        "UserPromptSubmit" => {
            let prompt = raw_value.get("prompt").and_then(|v| v.as_str())?;
            if event.tool_id == "codex" {
                (extract_codex_skill_mentions(prompt), "explicit_prompt")
            } else {
                (
                    extract_skill_from_slash_command(prompt)
                        .into_iter()
                        .collect(),
                    "explicit_prompt",
                )
            }
        }
        "Stop" if event.tool_id == "codex" => {
            let transcript_path = raw_value.get("transcript_path").and_then(|v| v.as_str())?;
            (
                extract_skill_ids_from_transcript(Path::new(transcript_path)),
                "transcript_fallback",
            )
        }
        _ => return None,
    };

    if skill_ids.is_empty() {
        return None;
    }

    Some(ExtractedUsage {
        skill_ids,
        session_id,
        turn_id,
        event_type: hook_event.to_string(),
        source,
    })
}

fn extract_skill_from_slash_command(prompt: &str) -> Option<String> {
    let trimmed = prompt.trim();
    if !trimmed.starts_with('/') {
        return None;
    }
    let after_slash = &trimmed[1..];
    let end = after_slash
        .find(|c: char| !c.is_alphanumeric() && c != '-' && c != '_')
        .unwrap_or(after_slash.len());
    if end == 0 {
        return None;
    }
    let skill_name = &after_slash[..end];
    if skill_name.is_empty() {
        return None;
    }
    let builtins = [
        "help",
        "clear",
        "compact",
        "config",
        "cost",
        "doctor",
        "exit",
        "init",
        "login",
        "logout",
        "memory",
        "model",
        "permissions",
        "review",
        "status",
        "terminal-setup",
        "vim",
        "bug",
        "resume",
        "release-notes",
        "feedback",
        "mcp",
        "usage",
    ];
    if builtins.contains(&skill_name) {
        return None;
    }
    Some(skill_name.to_string())
}

/// Codex officially uses `$skill-name`; `@skill-name` is also accepted here
/// for compatibility with composer surfaces that render mentions that way.
fn extract_codex_skill_mentions(prompt: &str) -> Vec<String> {
    let env_vars = [
        "HOME",
        "PATH",
        "USER",
        "SHELL",
        "TMPDIR",
        "LANG",
        "LC_ALL",
        "PWD",
        "OLDPWD",
        "TERM",
        "EDITOR",
        "VISUAL",
        "GOPATH",
        "GOROOT",
        "JAVA_HOME",
        "NODE_PATH",
        "PYTHONPATH",
        "RUSTUP_HOME",
        "CARGO_HOME",
    ];
    let mut result = Vec::new();
    let bytes = prompt.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'$' || bytes[i] == b'@' {
            // Mention must be at start or preceded by whitespace.
            if i > 0 {
                let prev = bytes[i - 1];
                if prev != b' ' && prev != b'\t' && prev != b'\n' && prev != b'\r' {
                    i += 1;
                    continue;
                }
            }
            // Extract name after $. Skill names must start with a letter
            // to avoid matching prices like $100.
            let rest = &prompt[i + 1..];
            let first = rest.chars().next();
            if first.is_none() || !first.unwrap().is_ascii_alphabetic() {
                i += 1;
                continue;
            }
            let end = rest
                .find(|c: char| !c.is_alphanumeric() && c != '-' && c != '_' && c != ':')
                .unwrap_or(rest.len());
            if end > 0 {
                let mention = &rest[..end];
                let name = mention.rsplit(':').next().unwrap_or(mention);
                if !env_vars.contains(&name) && !name.is_empty() {
                    result.push(name.to_string());
                }
            }
        }
        i += 1;
    }
    dedupe_skill_ids(result)
}

fn extract_skill_ids_from_value(tool_input: &serde_json::Value) -> Vec<String> {
    let mut result = Vec::new();
    if let Some(obj) = tool_input.as_object() {
        // "command" is used by WorkBuddy's Skill tool; others use skill_id/skill_name/name/skill
        for key in ["skill_id", "skill_name", "name", "skill", "command"] {
            if let Some(val) = obj.get(key) {
                if let Some(s) = val.as_str() {
                    if !s.is_empty() {
                        result.push(s.to_string());
                    }
                }
            }
        }
    }
    dedupe_skill_ids(result)
}

fn dedupe_skill_ids(ids: Vec<String>) -> Vec<String> {
    let mut seen = HashSet::new();
    ids.into_iter()
        .filter(|id| !id.is_empty() && seen.insert(id.clone()))
        .collect()
}

fn collect_string_values(value: &serde_json::Value, output: &mut Vec<String>) {
    match value {
        serde_json::Value::String(s) => output.push(s.clone()),
        serde_json::Value::Array(items) => {
            for item in items {
                collect_string_values(item, output);
            }
        }
        serde_json::Value::Object(obj) => {
            for value in obj.values() {
                collect_string_values(value, output);
            }
        }
        _ => {}
    }
}

fn extract_skill_ids_from_skill_paths(value: &serde_json::Value) -> Vec<String> {
    let mut strings = Vec::new();
    collect_string_values(value, &mut strings);
    dedupe_skill_ids(
        strings
            .iter()
            .flat_map(|value| extract_skill_ids_from_text(value))
            .collect(),
    )
}

fn extract_skill_ids_from_text(text: &str) -> Vec<String> {
    let normalized = text.replace('\\', "/");
    let lowercase = normalized.to_ascii_lowercase();
    let needle = "skill.md";
    let mut result = Vec::new();
    let mut search_from = 0;

    while let Some(relative) = lowercase[search_from..].find(needle) {
        let end = search_from + relative + needle.len();
        let mut start = search_from + relative;
        while start > 0 {
            let ch = normalized.as_bytes()[start - 1];
            if ch.is_ascii_whitespace()
                || matches!(
                    ch,
                    b'\''
                        | b'"'
                        | b'`'
                        | b'='
                        | b'('
                        | b')'
                        | b'['
                        | b']'
                        | b'{'
                        | b'}'
                        | b','
                        | b';'
                        | b'|'
                )
            {
                break;
            }
            start -= 1;
        }

        let candidate =
            normalized[start..end].trim_matches(|c: char| c == '\'' || c == '"' || c == '`');
        if let Some((parent, _)) = candidate.rsplit_once('/') {
            if let Some(skill_id) = parent.rsplit('/').next() {
                if !skill_id.is_empty() && skill_id != "." && skill_id != ".." {
                    result.push(skill_id.to_string());
                }
            }
        }
        search_from = end;
    }

    dedupe_skill_ids(result)
}

fn is_user_message_record(value: &serde_json::Value) -> bool {
    let payload = value.get("payload").unwrap_or(value);
    payload.get("type").and_then(|v| v.as_str()) == Some("message")
        && payload.get("role").and_then(|v| v.as_str()) == Some("user")
}

fn is_tool_call_record(value: &serde_json::Value) -> bool {
    fn contains_tool_call(value: &serde_json::Value) -> bool {
        match value {
            serde_json::Value::Object(obj) => {
                if obj
                    .get("type")
                    .and_then(|v| v.as_str())
                    .map(|kind| {
                        kind == "function_call" || kind == "custom_tool_call" || kind == "tool_call"
                    })
                    .unwrap_or(false)
                {
                    return true;
                }
                obj.values().any(contains_tool_call)
            }
            serde_json::Value::Array(items) => items.iter().any(contains_tool_call),
            _ => false,
        }
    }
    contains_tool_call(value)
}

fn extract_skill_ids_from_transcript(path: &Path) -> Vec<String> {
    let mut file = match fs::File::open(path) {
        Ok(file) => file,
        Err(_) => return Vec::new(),
    };
    let len = file.metadata().map(|meta| meta.len()).unwrap_or(0);
    let start = len.saturating_sub(TRANSCRIPT_TAIL_BYTES);
    if file.seek(SeekFrom::Start(start)).is_err() {
        return Vec::new();
    }
    let mut content = String::new();
    if file.read_to_string(&mut content).is_err() {
        return Vec::new();
    }
    if start > 0 {
        if let Some(first_newline) = content.find('\n') {
            content = content[first_newline + 1..].to_string();
        }
    }

    let records: Vec<serde_json::Value> = content
        .lines()
        .filter_map(|line| serde_json::from_str(line).ok())
        .collect();
    let turn_start = records
        .iter()
        .rposition(is_user_message_record)
        .map(|index| index + 1)
        .unwrap_or(0);

    let mut ids = Vec::new();
    for record in records.iter().skip(turn_start) {
        if is_tool_call_record(record) {
            ids.extend(extract_skill_ids_from_skill_paths(record));
        }
    }
    dedupe_skill_ids(ids)
}

/// 解析一个 pending 文件并写入 SQLite
fn import_pending_file(conn: &Connection, file_path: &PathBuf) -> Result<usize, String> {
    let content =
        fs::read_to_string(file_path).map_err(|e| format!("Failed to read pending file: {}", e))?;
    let trimmed = content.trim();
    if trimmed.is_empty() {
        return Ok(0);
    }
    let event: UsageEvent = match serde_json::from_str(trimmed) {
        Ok(e) => e,
        Err(_) => return Ok(0),
    };
    let usage = match extract_usage(&event) {
        Some(usage) => usage,
        None => return Ok(0),
    };
    let mut inserted = 0;
    for skill_id in usage.skill_ids {
        let dedupe_key = match (&usage.session_id, &usage.turn_id) {
            (Some(session_id), Some(turn_id)) => Some(format!(
                "{}:{}:{}:{}",
                event.tool_id, session_id, turn_id, skill_id
            )),
            _ => None,
        };
        inserted += conn
            .execute(
                "INSERT OR IGNORE INTO usage_events
                 (skill_id, tool_id, event_type, ts, session_id, turn_id, source, dedupe_key)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8)",
                rusqlite::params![
                    skill_id,
                    &event.tool_id,
                    &usage.event_type,
                    event.ts,
                    usage.session_id.as_deref(),
                    usage.turn_id.as_deref(),
                    usage.source,
                    dedupe_key,
                ],
            )
            .map_err(|e| format!("Failed to insert usage event: {}", e))?;
    }
    Ok(inserted)
}

/// 扫描 pending 目录，导入所有文件到 SQLite，导入后删除
pub fn import_pending_events(conn: &Connection) -> Result<usize, String> {
    let dir = pending_dir();
    if !dir.exists() {
        return Ok(0);
    }
    let entries = fs::read_dir(&dir).map_err(|e| format!("Failed to read pending dir: {}", e))?;
    let mut count = 0;
    for entry in entries.flatten() {
        let path = entry.path();
        // 只处理 .json 文件，跳过 .tmp- 前缀的临时文件
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if !name.ends_with(".json") || name.starts_with(".tmp-") {
            continue;
        }
        match import_pending_file(conn, &path) {
            Ok(imported) => {
                count += imported;
                let _ = fs::remove_file(&path);
            }
            Err(_) => {
                // 导入出错，保留文件等待下次重试
            }
        }
    }
    Ok(count)
}

/// 迁移旧 logl 文件到 SQLite（一次性）
fn migrate_legacy_log(conn: &Connection) -> Result<usize, String> {
    let log_path = skills_manager_dir().join(LEGACY_LOG_FILE);
    if !log_path.exists() {
        return Ok(0);
    }
    let content =
        fs::read_to_string(&log_path).map_err(|e| format!("Failed to read legacy log: {}", e))?;
    let mut count = 0;
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let event: UsageEvent = match serde_json::from_str(line) {
            Ok(e) => e,
            Err(_) => continue,
        };
        let usage = match extract_usage(&event) {
            Some(usage) => usage,
            None => continue,
        };
        for skill_id in usage.skill_ids {
            let _ = conn.execute(
                "INSERT INTO usage_events
                 (skill_id, tool_id, event_type, ts, session_id, turn_id, source)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)",
                rusqlite::params![
                    skill_id,
                    &event.tool_id,
                    &usage.event_type,
                    event.ts,
                    usage.session_id.as_deref(),
                    usage.turn_id.as_deref(),
                    usage.source,
                ],
            );
            count += 1;
        }
    }
    // 迁移成功后删除旧 logl
    let _ = fs::remove_file(&log_path);
    Ok(count)
}

#[tauri::command]
pub fn get_skill_usage_stats() -> Result<HashMap<String, SkillUsageStats>, String> {
    let conn = open_db()?;
    // 先导入 pending 文件
    let _ = import_pending_events(&conn);

    let mut stmt = conn
        .prepare("SELECT skill_id, tool_id, COUNT(*) as cnt, MAX(ts) as last_ts FROM usage_events GROUP BY skill_id, tool_id")
        .map_err(|e| format!("Failed to prepare query: {}", e))?;

    let mut stats: HashMap<String, SkillUsageStats> = HashMap::new();
    let rows = stmt
        .query_map([], |row| {
            Ok((
                row.get::<_, String>(0)?,
                row.get::<_, String>(1)?,
                row.get::<_, u64>(2)?,
                row.get::<_, Option<i64>>(3)?,
            ))
        })
        .map_err(|e| format!("Failed to query usage: {}", e))?;

    for row in rows.flatten() {
        let (skill_id, tool_id, cnt, last_ts) = row;
        let entry = stats.entry(skill_id).or_default();
        entry.total += cnt;
        entry.by_tool.insert(tool_id, cnt);
        if let Some(ts) = last_ts {
            if ts > entry.last_called_at.unwrap_or(0) {
                entry.last_called_at = Some(ts);
            }
        }
    }
    Ok(stats)
}

#[tauri::command]
pub fn clear_usage_stats() -> Result<(), String> {
    let conn = open_db()?;
    conn.execute("DELETE FROM usage_events", [])
        .map_err(|e| format!("Failed to clear usage events: {}", e))?;
    // 清空 pending 目录
    let dir = pending_dir();
    if dir.exists() {
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let _ = fs::remove_file(entry.path());
            }
        }
    }
    Ok(())
}

#[tauri::command]
pub fn get_usage_hook_status() -> Result<bool, String> {
    Ok(is_hook_installed() && is_codex_hook_installed() && is_workbuddy_hook_installed())
}

fn claude_settings_path() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_default()
        .join(".claude")
        .join("settings.json")
}

/// 生成 hook 命令字符串
fn build_hook_command() -> String {
    let script_path = hook_script_path();
    if cfg!(target_os = "windows") {
        // Windows: PowerShell
        format!(
            "powershell -ExecutionPolicy Bypass -File \"{}\"",
            script_path.to_string_lossy()
        )
    } else {
        // Unix: bash
        format!("bash \"{}\"", script_path.to_string_lossy())
    }
}

fn find_sm_hook_entry_in(settings: &serde_json::Value, event_key: &str) -> Option<usize> {
    let hooks = settings.get("hooks")?;
    let event_arr = hooks.get(event_key)?;
    let arr = event_arr.as_array()?;
    for (i, entry) in arr.iter().enumerate() {
        if event_key == "PostToolUse" {
            let matcher = entry.get("matcher").and_then(|m| m.as_str()).unwrap_or("");
            if matcher != "Skill" {
                continue;
            }
        }
        let hook_list = entry.get("hooks").and_then(|h| h.as_array());
        if let Some(hooks) = hook_list {
            for h in hooks {
                let cmd = h.get("command").and_then(|c| c.as_str()).unwrap_or("");
                if cmd.contains(HOOK_MARKER)
                    || cmd.contains("claude-skill-usage.sh")
                    || cmd.contains("claude-skill-usage.ps1")
                {
                    return Some(i);
                }
            }
        }
    }
    None
}

fn is_hook_installed() -> bool {
    let settings_path = claude_settings_path();
    let content = match fs::read_to_string(&settings_path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let settings: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return false,
    };
    find_sm_hook_entry_in(&settings, "PostToolUse").is_some()
        || find_sm_hook_entry_in(&settings, "UserPromptSubmit").is_some()
}

#[tauri::command]
pub fn install_usage_hook() -> Result<(), String> {
    // 1. Write hook script
    let hook_dir = skills_manager_dir().join(HOOK_DIR);
    fs::create_dir_all(&hook_dir).map_err(|e| format!("Failed to create hook dir: {}", e))?;
    let script_path = hook_script_path();
    fs::write(&script_path, hook_script_content())
        .map_err(|e| format!("Failed to write hook script: {}", e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = fs::Permissions::from_mode(0o755);
        fs::set_permissions(&script_path, perms)
            .map_err(|e| format!("Failed to set hook script permissions: {}", e))?;
    }

    // 2. Create pending directory
    fs::create_dir_all(pending_dir())
        .map_err(|e| format!("Failed to create pending dir: {}", e))?;

    // 3. Inject into Claude Code settings.json
    let settings_path = claude_settings_path();
    if let Some(parent) = settings_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create .claude dir: {}", e))?;
    }

    let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Claude settings.json: {}", e))?;

    let hook_command = build_hook_command();

    if settings.get("hooks").is_none() {
        settings["hooks"] = serde_json::json!({});
    }

    // PostToolUse: matcher "Skill"
    remove_sm_entries(&mut settings, "PostToolUse");
    if settings["hooks"].get("PostToolUse").is_none() {
        settings["hooks"]["PostToolUse"] = serde_json::json!([]);
    }
    let post_entry = serde_json::json!({
        "matcher": "Skill",
        "hooks": [{
            "type": "command",
            "command": hook_command
        }]
    });
    settings["hooks"]["PostToolUse"]
        .as_array_mut()
        .expect("PostToolUse should be array")
        .push(post_entry);

    // UserPromptSubmit: no matcher
    remove_sm_entries(&mut settings, "UserPromptSubmit");
    if settings["hooks"].get("UserPromptSubmit").is_none() {
        settings["hooks"]["UserPromptSubmit"] = serde_json::json!([]);
    }
    let submit_entry = serde_json::json!({
        "hooks": [{
            "type": "command",
            "command": hook_command
        }]
    });
    settings["hooks"]["UserPromptSubmit"]
        .as_array_mut()
        .expect("UserPromptSubmit should be array")
        .push(submit_entry);

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize settings: {}", e))?;
    fs::write(&settings_path, output)
        .map_err(|e| format!("Failed to write Claude settings.json: {}", e))?;

    // Install Codex hooks as part of the same feature so failures are visible.
    install_codex_usage_hook_internal()?;
    install_workbuddy_usage_hook_internal()?;

    Ok(())
}

fn remove_sm_entries(settings: &mut serde_json::Value, event_key: &str) {
    while let Some(idx) = find_sm_hook_entry_in(settings, event_key) {
        if let Some(arr) = settings
            .get_mut("hooks")
            .and_then(|h| h.get_mut(event_key))
            .and_then(|p| p.as_array_mut())
        {
            arr.remove(idx);
        } else {
            break;
        }
    }
}

#[tauri::command]
pub fn uninstall_usage_hook() -> Result<(), String> {
    let settings_path = claude_settings_path();
    let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Claude settings.json: {}", e))?;

    remove_sm_entries(&mut settings, "PostToolUse");
    remove_sm_entries(&mut settings, "UserPromptSubmit");

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize settings: {}", e))?;
    fs::write(&settings_path, output)
        .map_err(|e| format!("Failed to write Claude settings.json: {}", e))?;

    uninstall_codex_usage_hook_internal()?;
    uninstall_workbuddy_usage_hook_internal()?;

    Ok(())
}

// ===== Codex hook install/uninstall =====

fn find_sm_hook_in_codex(settings: &serde_json::Value, event_key: &str) -> Option<usize> {
    let hooks = settings.get("hooks")?;
    let event_arr = hooks.get(event_key)?;
    let arr = event_arr.as_array()?;
    for (i, entry) in arr.iter().enumerate() {
        let hook_list = entry.get("hooks").and_then(|h| h.as_array());
        if let Some(hooks) = hook_list {
            for h in hooks {
                let cmd = h.get("command").and_then(|c| c.as_str()).unwrap_or("");
                if cmd.contains(CODEX_HOOK_MARKER)
                    || cmd.contains("codex-skill-usage.sh")
                    || cmd.contains("codex-skill-usage.ps1")
                {
                    return Some(i);
                }
            }
        }
    }
    None
}

fn remove_codex_sm_entries(settings: &mut serde_json::Value, event_key: &str) {
    while let Some(idx) = find_sm_hook_in_codex(settings, event_key) {
        if let Some(arr) = settings
            .get_mut("hooks")
            .and_then(|h| h.get_mut(event_key))
            .and_then(|p| p.as_array_mut())
        {
            arr.remove(idx);
        } else {
            break;
        }
    }
}

fn is_codex_hook_installed() -> bool {
    let hooks_path = codex_hooks_path();
    let content = match fs::read_to_string(&hooks_path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let settings: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return false,
    };
    ["UserPromptSubmit", "PostToolUse", "Stop"]
        .iter()
        .all(|event_key| find_sm_hook_in_codex(&settings, event_key).is_some())
}

fn add_codex_hook_entries(settings: &mut serde_json::Value, hook_command: &str) {
    if settings.get("hooks").is_none() {
        settings["hooks"] = serde_json::json!({});
    }

    for event_key in ["UserPromptSubmit", "PostToolUse", "Stop"] {
        remove_codex_sm_entries(settings, event_key);
        if settings["hooks"].get(event_key).is_none() {
            settings["hooks"][event_key] = serde_json::json!([]);
        }
    }

    settings["hooks"]["UserPromptSubmit"]
        .as_array_mut()
        .expect("UserPromptSubmit should be array")
        .push(serde_json::json!({
            "hooks": [{"type": "command", "command": hook_command}]
        }));

    // Bash catches normal SKILL.md reads. MCP matchers cover filesystem tools.
    settings["hooks"]["PostToolUse"]
        .as_array_mut()
        .expect("PostToolUse should be array")
        .push(serde_json::json!({
            "matcher": "^(Bash|mcp__.*)$",
            "hooks": [{"type": "command", "command": hook_command}]
        }));

    // Stop provides transcript_path and compensates for unified_exec calls that
    // PostToolUse does not expose yet.
    settings["hooks"]["Stop"]
        .as_array_mut()
        .expect("Stop should be array")
        .push(serde_json::json!({
            "hooks": [{"type": "command", "command": hook_command}]
        }));
}

/// Install Codex hooks into ~/.codex/hooks.json.
fn install_codex_usage_hook_internal() -> Result<(), String> {
    // 1. Write Codex hook script
    let hook_dir = skills_manager_dir().join(HOOK_DIR);
    fs::create_dir_all(&hook_dir).map_err(|e| format!("Failed to create hook dir: {}", e))?;
    let script_path = codex_hook_script_path();
    fs::write(&script_path, codex_hook_script_content())
        .map_err(|e| format!("Failed to write Codex hook script: {}", e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
    }

    // 2. Create pending directory (shared with Claude Code)
    fs::create_dir_all(pending_dir())
        .map_err(|e| format!("Failed to create pending dir: {}", e))?;

    // 3. Inject into ~/.codex/hooks.json
    let hooks_path = codex_hooks_path();
    if let Some(parent) = hooks_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create .codex dir: {}", e))?;
    }

    let content = fs::read_to_string(&hooks_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Codex hooks.json: {}", e))?;

    let hook_command = build_codex_hook_command();

    add_codex_hook_entries(&mut settings, &hook_command);

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize Codex hooks.json: {}", e))?;
    fs::write(&hooks_path, output)
        .map_err(|e| format!("Failed to write Codex hooks.json: {}", e))?;

    Ok(())
}

fn uninstall_codex_usage_hook_internal() -> Result<(), String> {
    let hooks_path = codex_hooks_path();
    if !hooks_path.exists() {
        return Ok(());
    }
    let content = fs::read_to_string(&hooks_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse Codex hooks.json: {}", e))?;

    for event_key in ["UserPromptSubmit", "PostToolUse", "Stop"] {
        remove_codex_sm_entries(&mut settings, event_key);
    }

    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize Codex hooks.json: {}", e))?;
    fs::write(&hooks_path, output)
        .map_err(|e| format!("Failed to write Codex hooks.json: {}", e))?;

    Ok(())
}

// ===== WorkBuddy hook install/uninstall =====

/// 构造 WorkBuddy marketplace 的 marketplace.json 内容
/// 声明 marketplace 包含一个 skills-manager-usage 插件
fn workbuddy_marketplace_manifest_json() -> serde_json::Value {
    serde_json::json!({
        "name": WORKBUDDY_MARKETPLACE_ID,
        "description": "Skills Manager local usage hook marketplace",
        "plugins": [
            {
                "name": WORKBUDDY_PLUGIN_ID,
                "description": "Skills Manager usage hook for WorkBuddy (auto-generated)",
                "source": "./skills-manager-usage",
                "version": "1.0.0"
            }
        ]
    })
}

/// 构造 WorkBuddy 插件的 plugin.json 内容
fn workbuddy_plugin_manifest_json() -> serde_json::Value {
    serde_json::json!({
        "name": WORKBUDDY_PLUGIN_ID,
        "version": "1.0.0",
        "description": "Skills Manager usage hook for WorkBuddy (auto-generated)",
        "author": {"name": "Skills Manager"},
        "license": "MIT",
        "hooks": "hooks/hooks.json"
    })
}

/// 构造 WorkBuddy 插件的 hooks.json 内容
fn workbuddy_plugin_hooks_json(hook_command: &str) -> serde_json::Value {
    serde_json::json!({
        "description": "Skills Manager usage hook for WorkBuddy",
        "hooks": {
            "PostToolUse": [
                {
                    "matcher": "Skill",
                    "hooks": [{"type": "command", "command": hook_command}]
                }
            ],
            "UserPromptSubmit": [
                {
                    "hooks": [{"type": "command", "command": hook_command}]
                }
            ]
        }
    })
}

/// 构造 known_marketplaces.json 中 skills-manager-local 条目
fn workbuddy_marketplace_entry(plugin_root: &Path) -> serde_json::Value {
    serde_json::json!({
        "type": "directory",
        "source": {
            "source": "directory",
            "path": plugin_root.to_string_lossy()
        },
        "installLocation": plugin_root.to_string_lossy(),
        "autoUpdate": false,
        "description": "Skills Manager local usage hook marketplace",
        "lastUpdated": current_iso8601()
    })
}

fn current_iso8601() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    format!("{}", secs)
}

fn workbuddy_plugin_enabled_key() -> String {
    format!("{}@{}", WORKBUDDY_PLUGIN_ID, WORKBUDDY_MARKETPLACE_ID)
}

/// 判断 WorkBuddy 插件是否已注册并启用
fn is_workbuddy_hook_installed() -> bool {
    // 1. marketplace.json 存在
    let marketplace_json_path = workbuddy_plugin_root()
        .join(".codebuddy-plugin")
        .join("marketplace.json");
    if !marketplace_json_path.exists() {
        return false;
    }
    // 2. 插件目录及关键文件存在
    let install_dir = workbuddy_plugin_install_dir();
    if !install_dir
        .join(".codebuddy-plugin")
        .join("plugin.json")
        .exists()
    {
        return false;
    }
    if !workbuddy_hook_script_path().exists() {
        return false;
    }

    // 3. known_marketplaces.json 含 skills-manager-local 条目
    let mp_path = workbuddy_known_marketplaces_path();
    let content = match fs::read_to_string(&mp_path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let marketplaces: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return false,
    };
    if marketplaces.get(WORKBUDDY_MARKETPLACE_ID).is_none() {
        return false;
    }

    // 4. settings.json 的 enabledPlugins 中插件已启用
    let settings_path = workbuddy_settings_path();
    let content = match fs::read_to_string(&settings_path) {
        Ok(c) => c,
        Err(_) => return false,
    };
    let settings: serde_json::Value = match serde_json::from_str(&content) {
        Ok(v) => v,
        Err(_) => return false,
    };
    settings
        .get("enabledPlugins")
        .and_then(|p| p.get(workbuddy_plugin_enabled_key()))
        .and_then(|v| v.as_bool())
        .unwrap_or(false)
}

/// 安装 WorkBuddy 使用统计 hook：
/// 创建本地 marketplace 目录 + marketplace.json + 插件目录 + plugin.json + hooks.json + 脚本
/// + 注册到 known_marketplaces.json + 在 settings.json 启用插件
fn install_workbuddy_usage_hook_internal() -> Result<(), String> {
    let marketplace_root = workbuddy_plugin_root();

    // 0. 清理旧结构残留（整个插件根目录），确保干净重建
    if marketplace_root.exists() {
        let _ = fs::remove_dir_all(&marketplace_root);
    }

    // 1. 创建 marketplace 目录结构
    let marketplace_meta_dir = marketplace_root.join(".codebuddy-plugin");
    fs::create_dir_all(&marketplace_meta_dir)
        .map_err(|e| format!("Failed to create marketplace meta dir: {}", e))?;

    // 2. 写入 marketplace.json（声明 plugins 数组）
    let marketplace_json_path = marketplace_meta_dir.join("marketplace.json");
    let marketplace_json = serde_json::to_string_pretty(&workbuddy_marketplace_manifest_json())
        .map_err(|e| format!("Failed to serialize marketplace.json: {}", e))?;
    fs::write(&marketplace_json_path, marketplace_json)
        .map_err(|e| format!("Failed to write marketplace.json: {}", e))?;

    // 3. 创建插件目录结构 <marketplace_root>/skills-manager-usage/
    let install_dir = workbuddy_plugin_install_dir();
    let plugin_meta_dir = install_dir.join(".codebuddy-plugin");
    let hooks_dir = install_dir.join("hooks");
    fs::create_dir_all(&plugin_meta_dir)
        .map_err(|e| format!("Failed to create plugin meta dir: {}", e))?;
    fs::create_dir_all(&hooks_dir).map_err(|e| format!("Failed to create hooks dir: {}", e))?;

    // 4. 写入 plugin.json
    let plugin_json_path = plugin_meta_dir.join("plugin.json");
    let plugin_json = serde_json::to_string_pretty(&workbuddy_plugin_manifest_json())
        .map_err(|e| format!("Failed to serialize plugin.json: {}", e))?;
    fs::write(&plugin_json_path, plugin_json)
        .map_err(|e| format!("Failed to write plugin.json: {}", e))?;

    // 5. 写入 hook 脚本
    let script_path = workbuddy_hook_script_path();
    fs::write(&script_path, workbuddy_hook_script_content())
        .map_err(|e| format!("Failed to write WorkBuddy hook script: {}", e))?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
    }

    // 6. 写入 hooks.json
    let hooks_json_path = hooks_dir.join("hooks.json");
    let hook_command = build_workbuddy_hook_command();
    let hooks_json = serde_json::to_string_pretty(&workbuddy_plugin_hooks_json(&hook_command))
        .map_err(|e| format!("Failed to serialize hooks.json: {}", e))?;
    fs::write(&hooks_json_path, hooks_json)
        .map_err(|e| format!("Failed to write hooks.json: {}", e))?;

    // 7. 创建 pending 目录（与 Claude Code/Codex 共享）
    fs::create_dir_all(pending_dir())
        .map_err(|e| format!("Failed to create pending dir: {}", e))?;

    // 8. 注册到 known_marketplaces.json
    let mp_path = workbuddy_known_marketplaces_path();
    if let Some(parent) = mp_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create marketplaces dir: {}", e))?;
    }
    let content = fs::read_to_string(&mp_path).unwrap_or_else(|_| "{}".to_string());
    let mut marketplaces: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse known_marketplaces.json: {}", e))?;
    marketplaces[WORKBUDDY_MARKETPLACE_ID] = workbuddy_marketplace_entry(&marketplace_root);
    let output = serde_json::to_string_pretty(&marketplaces)
        .map_err(|e| format!("Failed to serialize known_marketplaces.json: {}", e))?;
    fs::write(&mp_path, output)
        .map_err(|e| format!("Failed to write known_marketplaces.json: {}", e))?;

    // 9. 在 settings.json 的 enabledPlugins 中启用插件
    let settings_path = workbuddy_settings_path();
    if let Some(parent) = settings_path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create .workbuddy dir: {}", e))?;
    }
    let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
    let mut settings: serde_json::Value = serde_json::from_str(&content)
        .map_err(|e| format!("Failed to parse WorkBuddy settings.json: {}", e))?;
    if settings.get("enabledPlugins").is_none() {
        settings["enabledPlugins"] = serde_json::json!({});
    }
    settings["enabledPlugins"][workbuddy_plugin_enabled_key()] = serde_json::json!(true);
    let output = serde_json::to_string_pretty(&settings)
        .map_err(|e| format!("Failed to serialize WorkBuddy settings.json: {}", e))?;
    fs::write(&settings_path, output)
        .map_err(|e| format!("Failed to write WorkBuddy settings.json: {}", e))?;

    Ok(())
}

fn uninstall_workbuddy_usage_hook_internal() -> Result<(), String> {
    // 1. 从 settings.json 的 enabledPlugins 移除插件
    let settings_path = workbuddy_settings_path();
    if settings_path.exists() {
        let content = fs::read_to_string(&settings_path).unwrap_or_else(|_| "{}".to_string());
        let mut settings: serde_json::Value = serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse WorkBuddy settings.json: {}", e))?;
        if let Some(plugins) = settings
            .get_mut("enabledPlugins")
            .and_then(|p| p.as_object_mut())
        {
            plugins.remove(&workbuddy_plugin_enabled_key());
        }
        let output = serde_json::to_string_pretty(&settings)
            .map_err(|e| format!("Failed to serialize WorkBuddy settings.json: {}", e))?;
        fs::write(&settings_path, output)
            .map_err(|e| format!("Failed to write WorkBuddy settings.json: {}", e))?;
    }

    // 2. 从 known_marketplaces.json 移除 marketplace 条目
    let mp_path = workbuddy_known_marketplaces_path();
    if mp_path.exists() {
        let content = fs::read_to_string(&mp_path).unwrap_or_else(|_| "{}".to_string());
        let mut marketplaces: serde_json::Value = serde_json::from_str(&content)
            .map_err(|e| format!("Failed to parse known_marketplaces.json: {}", e))?;
        if let Some(obj) = marketplaces.as_object_mut() {
            obj.remove(WORKBUDDY_MARKETPLACE_ID);
        }
        let output = serde_json::to_string_pretty(&marketplaces)
            .map_err(|e| format!("Failed to serialize known_marketplaces.json: {}", e))?;
        fs::write(&mp_path, output)
            .map_err(|e| format!("Failed to write known_marketplaces.json: {}", e))?;
    }

    // 3. 删除插件目录
    let plugin_root = workbuddy_plugin_root();
    if plugin_root.exists() {
        let _ = fs::remove_dir_all(&plugin_root);
    }

    Ok(())
}

/// Ensure hook state matches the preference. Called on app startup.
/// Always rewrites the hook script to the latest version (handles upgrades).
pub fn sync_usage_hook_with_config() {
    let manager = ConfigManager::new();
    let config = match manager.load() {
        Ok(c) => c,
        Err(_) => return,
    };
    let enabled = config
        .preferences
        .map(|p| p.skill_usage_monitor)
        .unwrap_or(true);

    let installed = is_hook_installed();
    if enabled && !installed {
        let _ = install_usage_hook();
    } else if !enabled && installed {
        let _ = uninstall_usage_hook();
    } else if enabled && installed {
        // Hook already installed: still rewrite script to ensure latest version
        let hook_dir = skills_manager_dir().join(HOOK_DIR);
        let _ = fs::create_dir_all(&hook_dir);
        let script_path = hook_script_path();
        let _ = fs::write(&script_path, hook_script_content());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
        }
        let _ = fs::create_dir_all(pending_dir());
        // Also update command in settings.json if platform changed
        let settings_path = claude_settings_path();
        if let Ok(content) = fs::read_to_string(&settings_path) {
            if let Ok(mut settings) = serde_json::from_str::<serde_json::Value>(&content) {
                let expected_cmd = build_hook_command();
                let needs_update = ["PostToolUse", "UserPromptSubmit"].iter().any(|key| {
                    if let Some(arr) = settings
                        .get("hooks")
                        .and_then(|h| h.get(key))
                        .and_then(|a| a.as_array())
                    {
                        arr.iter().any(|entry| {
                            if let Some(hooks) = entry.get("hooks").and_then(|h| h.as_array()) {
                                hooks.iter().any(|h| {
                                    let cmd =
                                        h.get("command").and_then(|c| c.as_str()).unwrap_or("");
                                    cmd.contains(HOOK_MARKER) && cmd != expected_cmd
                                })
                            } else {
                                false
                            }
                        })
                    } else {
                        false
                    }
                });
                if needs_update {
                    remove_sm_entries(&mut settings, "PostToolUse");
                    remove_sm_entries(&mut settings, "UserPromptSubmit");
                    // Re-add entries with the correct command
                    if settings.get("hooks").is_none() {
                        settings["hooks"] = serde_json::json!({});
                    }
                    if settings["hooks"].get("PostToolUse").is_none() {
                        settings["hooks"]["PostToolUse"] = serde_json::json!([]);
                    }
                    settings["hooks"]["PostToolUse"]
                        .as_array_mut()
                        .unwrap()
                        .push(serde_json::json!({
                            "matcher": "Skill",
                            "hooks": [{"type": "command", "command": expected_cmd.clone()}]
                        }));
                    if settings["hooks"].get("UserPromptSubmit").is_none() {
                        settings["hooks"]["UserPromptSubmit"] = serde_json::json!([]);
                    }
                    settings["hooks"]["UserPromptSubmit"]
                        .as_array_mut()
                        .unwrap()
                        .push(serde_json::json!({
                            "hooks": [{"type": "command", "command": expected_cmd}]
                        }));
                    let _ = fs::write(
                        &settings_path,
                        serde_json::to_string_pretty(&settings).unwrap_or_default(),
                    );
                }
            }
        }
    }

    // === Codex hook sync ===
    let codex_installed = is_codex_hook_installed();
    if enabled && !codex_installed {
        let _ = install_codex_usage_hook_internal();
    } else if !enabled && codex_installed {
        let _ = uninstall_codex_usage_hook_internal();
    } else if enabled && codex_installed {
        // Hook already installed: rewrite script to ensure latest version
        let hook_dir = skills_manager_dir().join(HOOK_DIR);
        let _ = fs::create_dir_all(&hook_dir);
        let script_path = codex_hook_script_path();
        let _ = fs::write(&script_path, codex_hook_script_content());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
        }
        let _ = fs::create_dir_all(pending_dir());
        // Rebuild our three entries to update commands and migrate older installs.
        let hooks_path = codex_hooks_path();
        if let Ok(content) = fs::read_to_string(&hooks_path) {
            if let Ok(mut settings) = serde_json::from_str::<serde_json::Value>(&content) {
                let expected_cmd = build_codex_hook_command();
                add_codex_hook_entries(&mut settings, &expected_cmd);
                let _ = fs::write(
                    &hooks_path,
                    serde_json::to_string_pretty(&settings).unwrap_or_default(),
                );
            }
        }
    }

    // === WorkBuddy hook sync ===
    let workbuddy_installed = is_workbuddy_hook_installed();
    if enabled && !workbuddy_installed {
        let _ = install_workbuddy_usage_hook_internal();
    } else if !enabled && workbuddy_installed {
        let _ = uninstall_workbuddy_usage_hook_internal();
    } else if enabled && workbuddy_installed {
        // Hook already installed: rewrite plugin files to ensure latest version
        let marketplace_root = workbuddy_plugin_root();
        let marketplace_meta_dir = marketplace_root.join(".codebuddy-plugin");
        let install_dir = workbuddy_plugin_install_dir();
        let plugin_meta_dir = install_dir.join(".codebuddy-plugin");
        let hooks_dir = install_dir.join("hooks");
        let _ = fs::create_dir_all(&marketplace_meta_dir);
        let _ = fs::create_dir_all(&plugin_meta_dir);
        let _ = fs::create_dir_all(&hooks_dir);

        // marketplace.json
        let marketplace_json = serde_json::to_string_pretty(&workbuddy_marketplace_manifest_json())
            .unwrap_or_default();
        let _ = fs::write(marketplace_meta_dir.join("marketplace.json"), marketplace_json);

        // plugin.json
        let plugin_json = serde_json::to_string_pretty(&workbuddy_plugin_manifest_json())
            .unwrap_or_default();
        let _ = fs::write(plugin_meta_dir.join("plugin.json"), plugin_json);

        // hook script
        let script_path = workbuddy_hook_script_path();
        let _ = fs::write(&script_path, workbuddy_hook_script_content());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let _ = fs::set_permissions(&script_path, fs::Permissions::from_mode(0o755));
        }

        // hooks.json
        let hook_command = build_workbuddy_hook_command();
        let hooks_json = serde_json::to_string_pretty(&workbuddy_plugin_hooks_json(&hook_command))
            .unwrap_or_default();
        let _ = fs::write(hooks_dir.join("hooks.json"), hooks_json);

        // Refresh marketplace entry + enabledPlugins in case paths changed
        let mp_path = workbuddy_known_marketplaces_path();
        if let Ok(content) = fs::read_to_string(&mp_path) {
            if let Ok(mut marketplaces) = serde_json::from_str::<serde_json::Value>(&content) {
                marketplaces[WORKBUDDY_MARKETPLACE_ID] = workbuddy_marketplace_entry(&marketplace_root);
                let _ = fs::write(
                    &mp_path,
                    serde_json::to_string_pretty(&marketplaces).unwrap_or_default(),
                );
            }
        }
        let settings_path = workbuddy_settings_path();
        if let Ok(content) = fs::read_to_string(&settings_path) {
            if let Ok(mut settings) = serde_json::from_str::<serde_json::Value>(&content) {
                if settings.get("enabledPlugins").is_none() {
                    settings["enabledPlugins"] = serde_json::json!({});
                }
                settings["enabledPlugins"][workbuddy_plugin_enabled_key()] = serde_json::json!(true);
                let _ = fs::write(
                    &settings_path,
                    serde_json::to_string_pretty(&settings).unwrap_or_default(),
                );
            }
        }
    }
}

// ===== 文件监听 + 自动导入 =====

/// 文件监听器，用于在 lib.rs setup 中启动
static WATCHER_INITIALIZED: Mutex<bool> = Mutex::new(false);

/// 启动 pending 目录监听，新文件到达时导入到 SQLite 并 emit event
pub fn start_usage_watcher(app: AppHandle) {
    let mut guard = WATCHER_INITIALIZED
        .lock()
        .unwrap_or_else(|e| e.into_inner());
    if *guard {
        return;
    }
    *guard = true;
    drop(guard);

    // 确保目录存在
    let _ = fs::create_dir_all(pending_dir());

    // 启动时先迁移旧 logl + 导入现有 pending
    std::thread::spawn(move || {
        if let Ok(conn) = open_db() {
            let _ = migrate_legacy_log(&conn);
            let _ = import_pending_events(&conn);
            // 迁移后通知前端刷新
            let _ = app.emit("usage-stats-updated", ());
        }

        // 启动 notify 监听
        use notify::{Config, EventKind, RecommendedWatcher, RecursiveMode, Watcher};

        let pending = pending_dir();
        let app_clone = app.clone();
        let mut watcher: RecommendedWatcher = match Watcher::new(
            move |res: notify::Result<notify::Event>| {
                if let Ok(event) = res {
                    let should_import =
                        matches!(event.kind, EventKind::Create(_) | EventKind::Modify(_));
                    if !should_import {
                        return;
                    }
                    std::thread::sleep(std::time::Duration::from_millis(200));
                    if let Ok(conn) = open_db() {
                        let _ = import_pending_events(&conn);
                        let _ = app_clone.emit("usage-stats-updated", ());
                    }
                }
            },
            Config::default(),
        ) {
            Ok(w) => w,
            Err(_) => return,
        };

        let _ = watcher.watch(&pending, RecursiveMode::NonRecursive);

        // 保持线程存活
        loop {
            std::thread::sleep(std::time::Duration::from_secs(60));
        }
    });
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    static HOME_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

    fn with_temp_home<F: FnOnce(&Path)>(f: F) {
        let _guard = HOME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let tmp = std::env::temp_dir().join(format!(
            "sm-test-{}-{}",
            std::process::id(),
            std::time::SystemTime::now().elapsed().unwrap().as_nanos()
        ));
        let _ = fs::create_dir_all(&tmp);
        let old_home = std::env::var("HOME").ok();
        std::env::set_var("HOME", &tmp);
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| f(&tmp)));
        if let Some(old) = old_home {
            std::env::set_var("HOME", old);
        } else {
            std::env::remove_var("HOME");
        }
        let _ = fs::remove_dir_all(&tmp);
        if let Err(payload) = result {
            std::panic::resume_unwind(payload);
        }
    }

    /// 写入一个 pending 事件文件
    fn write_pending_event(home: &Path, raw_json: &str, tool_id: &str, ts: i64) -> PathBuf {
        let dir = home.join(".skills-manager").join(PENDING_DIR);
        fs::create_dir_all(&dir).unwrap();
        let escaped = raw_json.replace('\\', "\\\\").replace('"', "\\\"");
        let content = format!(
            r#"{{"raw":"{}","tool_id":"{}","ts":{}}}"#,
            escaped, tool_id, ts
        );
        let path = dir.join(format!("{}-1-1.json", ts));
        fs::write(&path, content).unwrap();
        path
    }

    #[test]
    fn extract_skill_id_tries_known_field_names() {
        let cases = [
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_id":"abc"}}"#,
                vec!["abc"],
            ),
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_name":"xyz"}}"#,
                vec!["xyz"],
            ),
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"name":"foo"}}"#,
                vec!["foo"],
            ),
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"bar"}}"#,
                vec!["bar"],
            ),
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"other":"val"}}"#,
                vec![],
            ),
            (
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill_id":""}}"#,
                vec![],
            ),
            (r#"{}"#, vec![]),
        ];
        for (raw_json, expected) in cases {
            let event = UsageEvent {
                raw: Some(raw_json.to_string()),
                tool_id: "claude-code".to_string(),
                ts: 0,
            };
            let got = extract_usage(&event)
                .map(|usage| usage.skill_ids)
                .unwrap_or_default();
            assert_eq!(got, expected, "failed for raw: {}", raw_json);
        }
    }

    #[test]
    fn extract_skill_id_from_slash_command() {
        let cases = [
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"/ab-testing 测试按钮"}"#,
                Some("ab-testing"),
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"/pdf"}"#,
                Some("pdf"),
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"请帮我设计实验"}"#,
                None,
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"/help"}"#,
                None,
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"/clear"}"#,
                None,
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":""}"#,
                None,
            ),
        ];
        for (raw_json, expected) in cases {
            let event = UsageEvent {
                raw: Some(raw_json.to_string()),
                tool_id: "claude-code".to_string(),
                ts: 0,
            };
            let got = extract_usage(&event).and_then(|usage| usage.skill_ids.into_iter().next());
            assert_eq!(got.as_deref(), expected, "failed for raw: {}", raw_json);
        }
    }

    #[test]
    fn get_skill_usage_stats_aggregates_by_skill_and_tool() {
        with_temp_home(|home| {
            let stdin1 = r#"{"hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill_id":"alpha"}}"#;
            let stdin2 = r#"{"hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill_id":"alpha"}}"#;
            let stdin3 = r#"{"hook_event_name":"UserPromptSubmit","prompt":"/beta 测试"}"#;

            write_pending_event(home, stdin1, "claude-code", 100);
            write_pending_event(home, stdin2, "claude-code", 101);
            write_pending_event(home, stdin3, "claude-code", 102);

            let stats = get_skill_usage_stats().expect("should parse");
            let alpha = stats.get("alpha").expect("alpha stats");
            assert_eq!(alpha.total, 2);
            assert_eq!(alpha.by_tool.get("claude-code"), Some(&2));

            let beta = stats.get("beta").expect("beta stats");
            assert_eq!(beta.total, 1);
            assert_eq!(beta.by_tool.get("claude-code"), Some(&1));

            assert_eq!(stats.len(), 2, "only alpha and beta should be counted");
        });
    }

    #[test]
    fn get_skill_usage_stats_returns_empty_when_no_events() {
        with_temp_home(|_home| {
            let stats = get_skill_usage_stats().expect("should succeed with empty result");
            assert!(stats.is_empty());
        });
    }

    #[test]
    fn open_db_migrates_existing_usage_table_without_losing_rows() {
        with_temp_home(|home| {
            let db_path = home.join(".skills-manager").join(USAGE_DB_FILE);
            fs::create_dir_all(db_path.parent().unwrap()).unwrap();
            let conn = Connection::open(&db_path).unwrap();
            conn.execute_batch(
                "CREATE TABLE usage_events (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    skill_id TEXT NOT NULL,
                    tool_id TEXT NOT NULL,
                    event_type TEXT NOT NULL,
                    ts INTEGER NOT NULL
                );
                INSERT INTO usage_events (skill_id, tool_id, event_type, ts)
                VALUES ('legacy-skill', 'claude-code', 'PostToolUse', 123);",
            )
            .unwrap();
            drop(conn);

            let migrated = open_db().expect("old schema should migrate");
            let columns: Vec<String> = migrated
                .prepare("PRAGMA table_info(usage_events)")
                .unwrap()
                .query_map([], |row| row.get(1))
                .unwrap()
                .flatten()
                .collect();
            for expected in ["session_id", "turn_id", "source", "dedupe_key"] {
                assert!(columns.iter().any(|column| column == expected));
            }
            drop(migrated);

            let stats = get_skill_usage_stats().expect("legacy row should remain queryable");
            assert_eq!(stats.get("legacy-skill").unwrap().total, 1);
        });
    }

    #[test]
    fn clear_usage_stats_removes_all_events() {
        with_temp_home(|home| {
            write_pending_event(
                home,
                r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"abc"}}"#,
                "claude-code",
                100,
            );
            // 触发导入
            let _ = get_skill_usage_stats();
            // 清空
            clear_usage_stats().expect("clear should succeed");
            // 再查
            let stats = get_skill_usage_stats().expect("should succeed");
            assert!(stats.is_empty(), "stats should be empty after clear");
        });
    }

    #[test]
    fn find_sm_hook_entry_detects_installed_hook() {
        let settings: serde_json::Value = serde_json::json!({
            "hooks": {
                "PostToolUse": [
                    {
                        "matcher": "Skill",
                        "hooks": [{
                            "type": "command",
                            "command": "bash \"/Users/x/.skills-manager/hooks/claude-skill-usage.sh\""
                        }]
                    }
                ],
                "UserPromptSubmit": [
                    {
                        "hooks": [{
                            "type": "command",
                            "command": "bash \"/Users/x/.skills-manager/hooks/claude-skill-usage.sh\""
                        }]
                    }
                ]
            }
        });
        assert_eq!(find_sm_hook_entry_in(&settings, "PostToolUse"), Some(0));
        assert_eq!(
            find_sm_hook_entry_in(&settings, "UserPromptSubmit"),
            Some(0)
        );
    }

    #[test]
    fn find_sm_hook_entry_ignores_non_sm_hooks() {
        let settings: serde_json::Value = serde_json::json!({
            "hooks": {
                "PostToolUse": [
                    {
                        "matcher": "Skill",
                        "hooks": [{
                            "type": "command",
                            "command": "some-other-script.sh"
                        }]
                    }
                ]
            }
        });
        assert_eq!(find_sm_hook_entry_in(&settings, "PostToolUse"), None);
    }

    #[test]
    fn install_and_uninstall_hook_preserves_other_settings() {
        with_temp_home(|home| {
            let claude_dir = home.join(".claude");
            fs::create_dir_all(&claude_dir).unwrap();
            let settings_path = claude_dir.join("settings.json");
            let original = serde_json::json!({
                "model": "kimi-k2",
                "hooks": {
                    "Notification": [{
                        "matcher": "Notification",
                        "hooks": [{"type": "command", "command": "afplay /x.mp3"}]
                    }],
                    "PostToolUse": [{
                        "matcher": "Bash",
                        "hooks": [{"type": "command", "command": "other-script.sh"}]
                    }]
                },
                "permissions": {"defaultMode": "bypassPermissions"}
            });
            fs::write(
                &settings_path,
                serde_json::to_string_pretty(&original).unwrap(),
            )
            .unwrap();

            install_usage_hook().expect("install should succeed");

            let after_install: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();

            assert_eq!(
                after_install.get("model").and_then(|m| m.as_str()),
                Some("kimi-k2")
            );
            assert_eq!(
                after_install
                    .get("permissions")
                    .and_then(|p| p.get("defaultMode"))
                    .and_then(|m| m.as_str()),
                Some("bypassPermissions")
            );
            let post = after_install
                .get("hooks")
                .and_then(|h| h.get("PostToolUse"))
                .unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(arr.len(), 2, "should have Bash + Skill entries");
            let skill_entry = arr
                .iter()
                .find(|e| e.get("matcher").and_then(|m| m.as_str()) == Some("Skill"));
            assert!(skill_entry.is_some(), "Skill matcher entry should be added");
            let notif = after_install
                .get("hooks")
                .and_then(|h| h.get("Notification"))
                .unwrap();
            assert_eq!(notif.as_array().unwrap().len(), 1);

            let script_path = home
                .join(".skills-manager")
                .join("hooks")
                .join(HOOK_SCRIPT_NAME_UNIX);
            assert!(script_path.exists(), "hook script should exist");
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let perms = fs::metadata(&script_path).unwrap().permissions().mode();
                assert_eq!(perms & 0o111, 0o111, "script should be executable");
            }

            assert_eq!(get_usage_hook_status().unwrap(), true);

            uninstall_usage_hook().expect("uninstall should succeed");
            let after_uninstall: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();
            let post = after_uninstall
                .get("hooks")
                .and_then(|h| h.get("PostToolUse"))
                .unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(arr.len(), 1, "only Bash entry should remain");
            assert_eq!(
                arr[0].get("matcher").and_then(|m| m.as_str()),
                Some("Bash"),
                "remaining entry should be Bash, not Skill"
            );
            assert_eq!(
                after_uninstall.get("model").and_then(|m| m.as_str()),
                Some("kimi-k2")
            );
            assert!(after_uninstall
                .get("hooks")
                .and_then(|h| h.get("Notification"))
                .is_some());

            assert_eq!(get_usage_hook_status().unwrap(), false);
        });
    }

    #[test]
    fn install_hook_is_idempotent() {
        with_temp_home(|home| {
            let claude_dir = home.join(".claude");
            fs::create_dir_all(&claude_dir).unwrap();
            fs::write(claude_dir.join("settings.json"), "{}").unwrap();

            install_usage_hook().expect("first install");
            install_usage_hook().expect("second install should not duplicate");

            let settings: serde_json::Value = serde_json::from_str(
                &fs::read_to_string(claude_dir.join("settings.json")).unwrap(),
            )
            .unwrap();
            let post = settings.get("hooks").unwrap().get("PostToolUse").unwrap();
            let arr = post.as_array().unwrap();
            assert_eq!(
                arr.len(),
                1,
                "should have exactly one Skill entry, not duplicated"
            );
        });
    }

    #[test]
    fn parse_real_claude_code_hook_output() {
        let real_raw = r#"{"session_id":"1fba2762","hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"skill":"ab-testing"},"tool_response":{"success":true,"commandName":"ab-testing"},"tool_use_id":"functions.Skill:0","duration_ms":3}"#;
        with_temp_home(|home| {
            write_pending_event(home, real_raw, "claude-code", 1783836828);

            let stats = get_skill_usage_stats().expect("should parse");
            assert_eq!(stats.len(), 1, "should have exactly one skill entry");
            let entry = stats
                .get("ab-testing")
                .expect("should find ab-testing skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("claude-code"), Some(&1));
            assert_eq!(entry.last_called_at, Some(1783836828));
        });
    }

    #[test]
    fn parse_real_slash_command_hook_output() {
        let stdin = r#"{"session_id":"abc","hook_event_name":"UserPromptSubmit","prompt":"/ab-testing 测试按钮颜色"}"#;
        with_temp_home(|home| {
            write_pending_event(home, stdin, "claude-code", 1783838000);

            let stats = get_skill_usage_stats().expect("should parse");
            assert_eq!(stats.len(), 1, "should have exactly one skill entry");
            let entry = stats
                .get("ab-testing")
                .expect("should find ab-testing skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("claude-code"), Some(&1));
        });
    }

    #[test]
    fn migrate_legacy_log_imports_old_events() {
        with_temp_home(|home| {
            // 创建旧 logl 文件
            let sm_dir = home.join(".skills-manager");
            fs::create_dir_all(&sm_dir).unwrap();
            let log_path = sm_dir.join(LEGACY_LOG_FILE);
            let stdin = r#"{"hook_event_name":"PostToolUse","tool_input":{"skill":"migrated"}}"#;
            let escaped = stdin.replace('\\', "\\\\").replace('"', "\\\"");
            let line = format!(
                r#"{{"raw":"{}","tool_id":"claude-code","ts":1000}}"#,
                escaped
            );
            fs::write(&log_path, line).unwrap();

            // 迁移
            let conn = open_db().unwrap();
            let count = migrate_legacy_log(&conn).unwrap();
            assert_eq!(count, 1);
            assert!(
                !log_path.exists(),
                "legacy logl should be deleted after migration"
            );

            // 查询
            let stats = get_skill_usage_stats().unwrap();
            assert_eq!(stats.get("migrated").unwrap().total, 1);
        });
    }

    // ===== Codex tests =====

    #[test]
    fn extract_codex_skill_mentions_parse_explicit_syntax() {
        let cases = [
            ("$ab-testing 请帮我设计实验", vec!["ab-testing"]),
            ("请帮我 $pdf 处理文档", vec!["pdf"]),
            ("$skill-creator", vec!["skill-creator"]),
            ("@ab-testing 请帮我设计实验", vec!["ab-testing"]),
            ("$codex-security:fix-finding", vec!["fix-finding"]),
            ("请帮我设计实验", vec![]),
            ("echo $HOME", vec![]),
            ("$HOME/.bashrc", vec![]),
            ("", vec![]),
            ("价格是 $100", vec![]),
            ("$ab-testing $pdf", vec!["ab-testing", "pdf"]),
        ];
        for (prompt, expected) in cases {
            let got = extract_codex_skill_mentions(prompt);
            assert_eq!(got, expected, "failed for prompt: {:?}", prompt);
        }
    }

    #[test]
    fn extract_skill_id_handles_codex_user_prompt_submit() {
        let cases = [
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"$ab-testing 测试按钮"}"#,
                Some("ab-testing"),
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"请帮我 $pdf 处理文档"}"#,
                Some("pdf"),
            ),
            (
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"请帮我设计实验"}"#,
                None,
            ),
        ];
        for (raw_json, expected) in cases {
            let event = UsageEvent {
                raw: Some(raw_json.to_string()),
                tool_id: "codex".to_string(),
                ts: 0,
            };
            let got = extract_usage(&event).and_then(|usage| usage.skill_ids.into_iter().next());
            assert_eq!(got.as_deref(), expected, "failed for raw: {}", raw_json);
        }
    }

    #[test]
    fn extract_codex_post_tool_use_reads_skill_paths() {
        let raw = r#"{"session_id":"session-a","turn_id":"turn-a","hook_event_name":"PostToolUse","tool_name":"Bash","tool_input":{"command":"sed -n '1,240p' /Users/test/.skills-manager/skills/ab-testing/SKILL.md && sed -n '1,80p' r2/openai-docs/SKILL.md"}}"#;
        let event = UsageEvent {
            raw: Some(raw.to_string()),
            tool_id: "codex".to_string(),
            ts: 0,
        };
        let usage = extract_usage(&event).expect("should extract skill paths");
        assert_eq!(usage.skill_ids, vec!["ab-testing", "openai-docs"]);
        assert_eq!(usage.session_id.as_deref(), Some("session-a"));
        assert_eq!(usage.turn_id.as_deref(), Some("turn-a"));
        assert_eq!(usage.source, "post_tool_use");
    }

    #[test]
    fn transcript_fallback_only_scans_tool_calls_after_latest_user_message() {
        with_temp_home(|home| {
            let transcript_path = home.join("transcript.jsonl");
            let lines = [
                serde_json::json!({
                    "type": "response_item",
                    "payload": {"type": "message", "role": "developer", "content": "all-skills/should-not-count/SKILL.md"}
                }),
                serde_json::json!({
                    "type": "response_item",
                    "payload": {"type": "message", "role": "user", "content": "自然语言请求"}
                }),
                serde_json::json!({
                    "type": "response_item",
                    "payload": {
                        "type": "function_call",
                        "name": "exec_command",
                        "arguments": "{\"cmd\":\"sed -n '1,240p' /Users/test/.skills-manager/skills/ab-testing/SKILL.md\"}"
                    }
                }),
                serde_json::json!({
                    "type": "response_item",
                    "payload": {"type": "function_call_output", "output": "references/false-positive/SKILL.md"}
                }),
            ];
            fs::write(
                &transcript_path,
                lines
                    .iter()
                    .map(serde_json::Value::to_string)
                    .collect::<Vec<_>>()
                    .join("\n"),
            )
            .unwrap();

            assert_eq!(
                extract_skill_ids_from_transcript(&transcript_path),
                vec!["ab-testing"]
            );
        });
    }

    #[test]
    fn codex_explicit_post_tool_and_stop_events_dedupe_per_turn() {
        with_temp_home(|home| {
            let transcript_path = home.join("transcript.jsonl");
            let transcript = [
                serde_json::json!({
                    "type": "response_item",
                    "payload": {"type": "message", "role": "user", "content": "$ab-testing test"}
                }),
                serde_json::json!({
                    "type": "response_item",
                    "payload": {
                        "type": "function_call",
                        "name": "exec_command",
                        "arguments": "{\"cmd\":\"cat /Users/test/.skills-manager/skills/ab-testing/SKILL.md\"}"
                    }
                }),
            ];
            fs::write(
                &transcript_path,
                transcript
                    .iter()
                    .map(serde_json::Value::to_string)
                    .collect::<Vec<_>>()
                    .join("\n"),
            )
            .unwrap();

            let explicit = r#"{"session_id":"session-a","turn_id":"turn-a","hook_event_name":"UserPromptSubmit","prompt":"$ab-testing test"}"#;
            let post = r#"{"session_id":"session-a","turn_id":"turn-a","hook_event_name":"PostToolUse","tool_name":"Bash","tool_input":{"command":"cat /Users/test/.skills-manager/skills/ab-testing/SKILL.md"}}"#;
            let stop = serde_json::json!({
                "session_id": "session-a",
                "turn_id": "turn-a",
                "hook_event_name": "Stop",
                "transcript_path": transcript_path,
            })
            .to_string();

            write_pending_event(home, explicit, "codex", 100);
            write_pending_event(home, post, "codex", 101);
            write_pending_event(home, &stop, "codex", 102);

            let stats = get_skill_usage_stats().expect("should import deduped events");
            let entry = stats.get("ab-testing").expect("ab-testing stats");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("codex"), Some(&1));
        });
    }

    #[test]
    fn codex_skill_usage_stats_aggregate_by_tool() {
        with_temp_home(|home| {
            let codex_prompt =
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"$ab-testing 测试按钮"}"#;
            let claude_prompt =
                r#"{"hook_event_name":"UserPromptSubmit","prompt":"/ab-testing 测试"}"#;

            write_pending_event(home, codex_prompt, "codex", 100);
            write_pending_event(home, claude_prompt, "claude-code", 101);

            let stats = get_skill_usage_stats().expect("should parse");
            let entry = stats.get("ab-testing").expect("ab-testing stats");
            assert_eq!(entry.total, 2);
            assert_eq!(entry.by_tool.get("codex"), Some(&1));
            assert_eq!(entry.by_tool.get("claude-code"), Some(&1));
        });
    }

    #[test]
    fn install_and_uninstall_codex_hook_preserves_other_hooks() {
        with_temp_home(|home| {
            let codex_dir = home.join(".codex");
            fs::create_dir_all(&codex_dir).unwrap();
            let hooks_path = codex_dir.join("hooks.json");
            let original = serde_json::json!({
                "hooks": {
                    "PostToolUse": [{
                        "matcher": "^Bash$",
                        "hooks": [{"type": "command", "command": "other-script.sh"}]
                    }],
                    "UserPromptSubmit": [{
                        "hooks": [{"type": "command", "command": "other-notify.py"}]
                    }]
                }
            });
            fs::write(
                &hooks_path,
                serde_json::to_string_pretty(&original).unwrap(),
            )
            .unwrap();

            install_codex_usage_hook_internal().expect("install should succeed");

            let after_install: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&hooks_path).unwrap()).unwrap();

            // Other hooks preserved
            let post = after_install
                .get("hooks")
                .and_then(|h| h.get("PostToolUse"))
                .unwrap();
            assert_eq!(
                post.as_array().unwrap().len(),
                2,
                "PostToolUse should preserve other + sm entries"
            );
            let submit = after_install
                .get("hooks")
                .and_then(|h| h.get("UserPromptSubmit"))
                .unwrap();
            let arr = submit.as_array().unwrap();
            assert_eq!(
                arr.len(),
                2,
                "UserPromptSubmit should have other + sm entries"
            );
            let stop = after_install
                .get("hooks")
                .and_then(|h| h.get("Stop"))
                .unwrap();
            assert_eq!(
                stop.as_array().unwrap().len(),
                1,
                "Stop should have the sm entry"
            );

            // Codex hook script exists
            let script_path = home
                .join(".skills-manager")
                .join("hooks")
                .join(CODEX_HOOK_SCRIPT_NAME_UNIX);
            assert!(script_path.exists(), "codex hook script should exist");
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                let perms = fs::metadata(&script_path).unwrap().permissions().mode();
                assert_eq!(perms & 0o111, 0o111, "script should be executable");
            }

            assert!(
                is_codex_hook_installed(),
                "codex hook should be detected as installed"
            );

            uninstall_codex_usage_hook_internal().expect("uninstall should succeed");
            let after_uninstall: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&hooks_path).unwrap()).unwrap();
            let submit = after_uninstall
                .get("hooks")
                .and_then(|h| h.get("UserPromptSubmit"))
                .unwrap();
            let arr = submit.as_array().unwrap();
            assert_eq!(arr.len(), 1, "only other entry should remain");
            assert_eq!(
                arr[0]
                    .get("hooks")
                    .unwrap()
                    .get(0)
                    .unwrap()
                    .get("command")
                    .and_then(|c| c.as_str()),
                Some("other-notify.py"),
                "remaining entry should be the other hook"
            );
            let post = after_uninstall
                .get("hooks")
                .and_then(|h| h.get("PostToolUse"))
                .unwrap();
            assert_eq!(
                post.as_array().unwrap().len(),
                1,
                "other PostToolUse should remain"
            );
            let stop = after_uninstall
                .get("hooks")
                .and_then(|h| h.get("Stop"))
                .unwrap();
            assert!(
                stop.as_array().unwrap().is_empty(),
                "sm Stop entry should be removed"
            );

            assert!(
                !is_codex_hook_installed(),
                "codex hook should be detected as uninstalled"
            );
        });
    }

    #[test]
    fn install_codex_hook_is_idempotent() {
        with_temp_home(|home| {
            let codex_dir = home.join(".codex");
            fs::create_dir_all(&codex_dir).unwrap();
            fs::write(codex_dir.join("hooks.json"), "{}").unwrap();

            install_codex_usage_hook_internal().expect("first install");
            install_codex_usage_hook_internal().expect("second install should not duplicate");

            let settings: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(codex_dir.join("hooks.json")).unwrap())
                    .unwrap();
            for event_key in ["UserPromptSubmit", "PostToolUse", "Stop"] {
                let entries = settings.get("hooks").unwrap().get(event_key).unwrap();
                assert_eq!(
                    entries.as_array().unwrap().len(),
                    1,
                    "{} should have exactly one sm entry",
                    event_key
                );
            }
        });
    }

    #[test]
    fn parse_real_codex_hook_output() {
        let raw = r#"{"session_id":"abc","hook_event_name":"UserPromptSubmit","prompt":"$ab-testing 测试按钮颜色","cwd":"/tmp/project","model":"gpt-5"}"#;
        with_temp_home(|home| {
            write_pending_event(home, raw, "codex", 1783839000);

            let stats = get_skill_usage_stats().expect("should parse");
            assert_eq!(stats.len(), 1, "should have exactly one skill entry");
            let entry = stats
                .get("ab-testing")
                .expect("should find ab-testing skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("codex"), Some(&1));
            assert_eq!(entry.last_called_at, Some(1783839000));
        });
    }

    #[test]
    fn workbuddy_install_creates_plugin_files_and_registrations() {
        with_temp_home(|home| {
            // 安装前未安装
            assert!(!is_workbuddy_hook_installed());

            install_workbuddy_usage_hook_internal().expect("install should succeed");

            // 1. marketplace.json 存在且含 plugins 数组
            let marketplace_root = home.join(".skills-manager").join("hooks").join("workbuddy-plugin");
            let marketplace_json_path = marketplace_root.join(".codebuddy-plugin").join("marketplace.json");
            assert!(marketplace_json_path.exists(), "marketplace.json should exist");
            let marketplace_json: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&marketplace_json_path).unwrap()).unwrap();
            assert_eq!(
                marketplace_json.get("name").and_then(|v| v.as_str()),
                Some(WORKBUDDY_MARKETPLACE_ID)
            );
            let plugins = marketplace_json.get("plugins").and_then(|v| v.as_array()).unwrap();
            assert_eq!(plugins.len(), 1);
            assert_eq!(
                plugins[0].get("name").and_then(|v| v.as_str()),
                Some(WORKBUDDY_PLUGIN_ID)
            );

            // 2. 插件目录及关键文件存在
            let install_dir = marketplace_root.join("skills-manager-usage");
            let plugin_json_path = install_dir.join(".codebuddy-plugin").join("plugin.json");
            let hooks_json_path = install_dir.join("hooks").join("hooks.json");
            let script_name = if cfg!(target_os = "windows") {
                WORKBUDDY_HOOK_SCRIPT_NAME_WIN
            } else {
                WORKBUDDY_HOOK_SCRIPT_NAME_UNIX
            };
            let script_path = install_dir.join("hooks").join(script_name);
            assert!(plugin_json_path.exists(), "plugin.json should exist");
            assert!(hooks_json_path.exists(), "hooks.json should exist");
            assert!(script_path.exists(), "hook script should exist");

            // 3. plugin.json 含正确字段
            let plugin_json: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&plugin_json_path).unwrap()).unwrap();
            assert_eq!(
                plugin_json.get("name").and_then(|v| v.as_str()),
                Some(WORKBUDDY_PLUGIN_ID)
            );
            assert_eq!(
                plugin_json.get("hooks").and_then(|v| v.as_str()),
                Some("hooks/hooks.json")
            );

            // 4. hooks.json 含 PostToolUse + UserPromptSubmit
            let hooks_json: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&hooks_json_path).unwrap()).unwrap();
            let hooks = hooks_json.get("hooks").unwrap();
            assert!(hooks.get("PostToolUse").is_some());
            assert!(hooks.get("UserPromptSubmit").is_some());

            // 5. known_marketplaces.json 含 skills-manager-local 条目
            let mp_path = home
                .join(".workbuddy")
                .join("plugins")
                .join("known_marketplaces.json");
            let mp: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&mp_path).unwrap()).unwrap();
            assert!(mp.get(WORKBUDDY_MARKETPLACE_ID).is_some());

            // 6. settings.json 的 enabledPlugins 启用插件
            let settings_path = home.join(".workbuddy").join("settings.json");
            let settings: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();
            let enabled = settings
                .get("enabledPlugins")
                .and_then(|p| p.get(workbuddy_plugin_enabled_key()))
                .and_then(|v| v.as_bool())
                .unwrap_or(false);
            assert!(enabled, "plugin should be enabled in settings.json");

            // 状态检测应返回 true
            assert!(is_workbuddy_hook_installed());
        });
    }

    #[test]
    fn workbuddy_uninstall_removes_plugin_files_and_registrations() {
        with_temp_home(|home| {
            install_workbuddy_usage_hook_internal().expect("install should succeed");
            assert!(is_workbuddy_hook_installed());

            uninstall_workbuddy_usage_hook_internal().expect("uninstall should succeed");

            // 插件目录应被删除
            let plugin_root = home.join(".skills-manager").join("hooks").join("workbuddy-plugin");
            assert!(!plugin_root.exists(), "plugin dir should be removed");

            // known_marketplaces.json 应不再含 skills-manager-local
            let mp_path = home
                .join(".workbuddy")
                .join("plugins")
                .join("known_marketplaces.json");
            let mp: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&mp_path).unwrap()).unwrap();
            assert!(mp.get(WORKBUDDY_MARKETPLACE_ID).is_none());

            // settings.json 的 enabledPlugins 应不再含插件
            let settings_path = home.join(".workbuddy").join("settings.json");
            let settings: serde_json::Value =
                serde_json::from_str(&fs::read_to_string(&settings_path).unwrap()).unwrap();
            assert!(settings
                .get("enabledPlugins")
                .and_then(|p| p.get(workbuddy_plugin_enabled_key()))
                .is_none());

            assert!(!is_workbuddy_hook_installed());
        });
    }

    #[test]
    fn workbuddy_skill_tool_command_field_is_extracted() {
        // WorkBuddy 的 Skill 工具使用 command 字段传递 skill 名称
        let raw = r#"{"hook_event_name":"PostToolUse","tool_name":"Skill","tool_input":{"command":"animate"}}"#;
        with_temp_home(|home| {
            write_pending_event(home, raw, "workbuddy", 1783840000);

            let stats = get_skill_usage_stats().expect("should parse");
            let entry = stats.get("animate").expect("should find animate skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("workbuddy"), Some(&1));
        });
    }

    #[test]
    fn workbuddy_userpromptsubmit_counts_via_slash_command() {
        let raw = r#"{"hook_event_name":"UserPromptSubmit","prompt":"/pdf 帮我生成报告"}"#;
        with_temp_home(|home| {
            write_pending_event(home, raw, "workbuddy", 1783841000);

            let stats = get_skill_usage_stats().expect("should parse");
            let entry = stats.get("pdf").expect("should find pdf skill");
            assert_eq!(entry.total, 1);
            assert_eq!(entry.by_tool.get("workbuddy"), Some(&1));
        });
    }

    #[test]
    fn workbuddy_install_is_idempotent() {
        with_temp_home(|_home| {
            install_workbuddy_usage_hook_internal().expect("first install");
            // 重复安装不应报错，也不应产生重复条目
            install_workbuddy_usage_hook_internal().expect("second install should not fail");

            assert!(is_workbuddy_hook_installed());
        });
    }
}
