"""Validated global defaults for Discovery Launch execution.

The settings surface deliberately owns only the parameters that are part of the
Discovery workflow contract.  It does not mirror the complete YAML configuration
tree: paths, memory stores, providers' transport details, resource allocation, and
other implementation details stay outside this module.

The module is intentionally deep at its seam.  Callers only need ``get``, ``save``,
and ``snapshot``; type/range/enum validation, complete-shape checks, and durable
atomic replacement are kept here so every caller observes the same contract.
"""

from __future__ import annotations

import copy
import json
import math
import os
import tempfile
from pathlib import Path
from typing import Any, Mapping


class DiscoveryPreferencesValidationError(ValueError):
    """Raised when a proposed Discovery Launch preference set is invalid."""

    def __init__(self, message: str, violations: list[dict[str, Any]] | None = None):
        super().__init__(message)
        self.violations = violations or []

    def to_dict(self) -> dict[str, Any]:
        result: dict[str, Any] = {"message": str(self)}
        if self.violations:
            result["violations"] = copy.deepcopy(self.violations)
        return result


# This is the only user-editable parameter set for the Discovery Launch module.
# Defaults intentionally mirror config/default_config.yaml and launch_discovery.py.
DEFAULT_DISCOVERY_LAUNCH_PREFERENCES: dict[str, Any] = {
    "backend": "codex",
    "skip_idea_generation": False,
    "workflow": {
        "loop_rounds": 10,
        "loop_mode": "incremental",
        "max_iterations": 4,
        "top_ideas_count": 5,
        "top_ideas_evo": True,
        "max_concurrent_tasks": 5,
    },
    "agents": {
        "generation": {
            "generation_count": 15,
            "creativity": 0.7,
            "failed_similarity_threshold": 0.7,
        },
        "reflection": {
            "count": 3,
            "detail_level": "medium",
        },
        "evolution": {
            "creativity_level": 0.6,
            "temperature": 0.7,
            "use_memory": True,
        },
        "ranking": {
            "criteria": {
                "novelty": 0.3,
                "plausibility": 0.4,
                "testability": 0.2,
                "alignment": 0.1,
            },
            "strategy": "default",
        },
        "scholar": {
            "search_depth": "moderate",
        },
        "survey": {
            "max_papers": 50,
        },
        "dr": {
            "enabled": True,
            "mode": "simple",
        },
        "exp_analyze": {
            "use_llm_for_metric_direction": True,
        },
    },
    "experiment": {
        "max_runs": 2,
        "use_mcts": False,
    },
}


_PARAMETER_DEFINITIONS: dict[str, dict[str, Any]] = {
    "backend": {
        "type": "enum",
        "values": ["codex", "qwen_code", "openhands"],
        "description": "Coding-agent backend used by a newly admitted Discovery Launch.",
    },
    "skip_idea_generation": {
        "type": "boolean",
        "description": "Skip MAS idea generation and load the existing idea input.",
    },
    "workflow.loop_rounds": {
        "type": "integer",
        "minimum": 1,
        "description": "Maximum number of complete Discovery rounds.",
    },
    "workflow.loop_mode": {
        "type": "enum",
        "values": ["fresh", "incremental"],
        "description": "Whether each round starts fresh or carries forward the best result.",
    },
    "workflow.max_iterations": {
        "type": "integer",
        "minimum": 1,
        "description": "Maximum MAS refinement iterations within a round.",
    },
    "workflow.top_ideas_count": {
        "type": "integer",
        "minimum": 1,
        "description": "Number of ranked ideas sent to Candidate Experiment execution.",
    },
    "workflow.top_ideas_evo": {
        "type": "boolean",
        "description": "Include the selected top ideas in later evolution work.",
    },
    "workflow.max_concurrent_tasks": {
        "type": "integer",
        "minimum": 1,
        "description": "Maximum concurrent Discovery workflow tasks.",
    },
    "agents.generation.generation_count": {
        "type": "integer",
        "minimum": 1,
        "description": "Initial ideas generated by the Generation Agent per round.",
    },
    "agents.generation.creativity": {
        "type": "number",
        "minimum": 0.0,
        "maximum": 1.0,
        "description": "Exploration level used for initial idea generation.",
    },
    "agents.generation.failed_similarity_threshold": {
        "type": "number",
        "minimum": 0.0,
        "maximum": 1.0,
        "description": "Similarity threshold for rejecting ideas close to failed attempts.",
    },
    "agents.reflection.count": {
        "type": "integer",
        "minimum": 1,
        "description": "Reflection passes applied to each generated idea.",
    },
    "agents.reflection.detail_level": {
        "type": "enum",
        "values": ["low", "medium", "high"],
        "description": "Amount of detail produced by each reflection pass.",
    },
    "agents.evolution.creativity_level": {
        "type": "number",
        "minimum": 0.0,
        "maximum": 1.0,
        "description": "Exploration level used when evolving existing ideas.",
    },
    "agents.evolution.temperature": {
        "type": "number",
        "minimum": 0.0,
        "maximum": 2.0,
        "description": "Sampling temperature used for evolved idea variants.",
    },
    "agents.evolution.use_memory": {
        "type": "boolean",
        "description": "Allow the Evolution Agent to use its configured memory context.",
    },
    "agents.ranking.criteria": {
        "type": "object",
        "properties": ["novelty", "plausibility", "testability", "alignment"],
        "minimum": 0.0,
        "maximum": 1.0,
        "sum": 1.0,
        "description": "Relative ranking weights; the four weights must sum to 1.",
    },
    "agents.ranking.strategy": {
        "type": "enum",
        "values": ["default", "distinct"],
        "description": "Ranking strategy used to select candidate ideas.",
    },
    "agents.scholar.search_depth": {
        "type": "enum",
        "values": ["shallow", "moderate", "deep"],
        "description": "Depth of Scholar literature searches.",
    },
    "agents.survey.max_papers": {
        "type": "integer",
        "minimum": 1,
        "description": "Maximum papers considered by the Survey Agent.",
    },
    "agents.dr.enabled": {
        "type": "boolean",
        "description": "Enable the background Deep Research Agent phase.",
    },
    "agents.dr.mode": {
        "type": "enum",
        "values": ["simple", "complex", "qa"],
        "description": "Deep Research Agent operating mode.",
    },
    "agents.exp_analyze.use_llm_for_metric_direction": {
        "type": "boolean",
        "description": "Use an LLM to determine metric direction during analysis.",
    },
    "experiment.max_runs": {
        "type": "integer",
        "minimum": 1,
        "description": "Maximum Experiment Runs per Candidate Experiment.",
    },
    "experiment.use_mcts": {
        "type": "boolean",
        "description": "Use the configured MCTS experiment adapter.",
    },
}


_EXPECTED_SHAPE = DEFAULT_DISCOVERY_LAUNCH_PREFERENCES


def _path_value(values: Mapping[str, Any], path: str) -> Any:
    current: Any = values
    for part in path.split("."):
        if not isinstance(current, Mapping) or part not in current:
            raise KeyError(path)
        current = current[part]
    return current


def _violation(path: str, message: str) -> dict[str, str]:
    return {"path": path, "message": message}


def _is_number(value: Any) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def _validate_shape_and_values(values: Any) -> dict[str, Any]:
    violations: list[dict[str, Any]] = []

    if not isinstance(values, dict):
        raise DiscoveryPreferencesValidationError(
            "Discovery Launch preferences must be an object",
            [_violation("", "an object is required")],
        )

    def walk_shape(candidate: Any, expected: Any, path: str) -> Any:
        if isinstance(expected, dict):
            if not isinstance(candidate, dict):
                violations.append(_violation(path, "an object is required"))
                return None
            expected_keys = set(expected)
            actual_keys = set(candidate)
            for unknown in sorted(actual_keys - expected_keys):
                unknown_path = f"{path}.{unknown}" if path else unknown
                violations.append(_violation(unknown_path, "unknown parameter"))
            for missing in sorted(expected_keys - actual_keys):
                missing_path = f"{path}.{missing}" if path else missing
                violations.append(_violation(missing_path, "parameter is required"))
            return {
                key: walk_shape(candidate[key], expected[key], f"{path}.{key}" if path else key)
                for key in sorted(actual_keys & expected_keys)
            }
        return candidate

    normalized = walk_shape(values, _EXPECTED_SHAPE, "")
    if violations:
        raise DiscoveryPreferencesValidationError(
            "Discovery Launch preferences contain unknown or missing parameters",
            violations,
        )

    for path, definition in _PARAMETER_DEFINITIONS.items():
        try:
            value = _path_value(values, path)
        except KeyError:
            continue
        kind = definition["type"]
        if kind == "boolean":
            if not isinstance(value, bool):
                violations.append(_violation(path, "must be a boolean"))
        elif kind == "integer":
            if isinstance(value, bool) or not isinstance(value, int):
                violations.append(_violation(path, "must be an integer"))
            elif value < definition["minimum"]:
                violations.append(
                    _violation(path, f"must be at least {definition['minimum']}")
                )
        elif kind == "number":
            if not _is_number(value) or not math.isfinite(float(value)):
                violations.append(_violation(path, "must be a finite number"))
            else:
                numeric = float(value)
                if numeric < definition["minimum"] or numeric > definition["maximum"]:
                    violations.append(
                        _violation(
                            path,
                            f"must be between {definition['minimum']} and {definition['maximum']}",
                        )
                    )
        elif kind == "enum" and value not in definition["values"]:
            values_text = ", ".join(definition["values"])
            violations.append(_violation(path, f"must be one of: {values_text}"))
        elif kind == "object":
            if not isinstance(value, dict):
                violations.append(_violation(path, "must be an object"))
            else:
                expected_criteria = set(definition["properties"])
                actual_criteria = set(value)
                for unknown in sorted(actual_criteria - expected_criteria):
                    violations.append(_violation(f"{path}.{unknown}", "unknown ranking weight"))
                for missing in sorted(expected_criteria - actual_criteria):
                    violations.append(_violation(f"{path}.{missing}", "ranking weight is required"))
                total = 0.0
                for key in sorted(actual_criteria & expected_criteria):
                    weight = value[key]
                    if not _is_number(weight) or not math.isfinite(float(weight)):
                        violations.append(_violation(f"{path}.{key}", "must be a finite number"))
                    elif float(weight) < 0.0 or float(weight) > 1.0:
                        violations.append(_violation(f"{path}.{key}", "must be between 0 and 1"))
                    else:
                        total += float(weight)
                if expected_criteria.issubset(actual_criteria) and not math.isclose(
                    total, 1.0, rel_tol=0.0, abs_tol=1e-6
                ):
                    violations.append(_violation(path, "ranking weights must sum to 1"))

    if violations:
        raise DiscoveryPreferencesValidationError(
            "Discovery Launch preferences failed validation", violations
        )

    # JSON has no separate integer/float distinction for settings consumers.  Keep the
    # declared integer fields as integers and normalize all accepted numeric weights and
    # sampling values to floats for deterministic snapshots.
    normalized_values = copy.deepcopy(values)
    for path, definition in _PARAMETER_DEFINITIONS.items():
        if definition["type"] != "number":
            continue
        parent: Any = normalized_values
        parts = path.split(".")
        for part in parts[:-1]:
            parent = parent[part]
        parent[parts[-1]] = float(parent[parts[-1]])
    criteria = normalized_values["agents"]["ranking"]["criteria"]
    for key in criteria:
        criteria[key] = float(criteria[key])
    return normalized_values


class DiscoveryLaunchPreferences:
    """Own validated global Discovery Launch defaults and their atomic storage."""

    schema_version = 1

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self._values = copy.deepcopy(DEFAULT_DISCOVERY_LAUNCH_PREFERENCES)
        self._load()

    def _load(self) -> None:
        try:
            payload = json.loads(self.path.read_text(encoding="utf-8"))
        except (FileNotFoundError, OSError, json.JSONDecodeError):
            return
        if not isinstance(payload, dict):
            return
        stored_version = payload.get("schema_version")
        if stored_version is not None and stored_version != self.schema_version:
            return
        values = payload.get("values", payload)
        # Backend was added as a top-level setting.  Preserve older valid settings
        # files by applying the installed default only when the field is absent;
        # Removed backend identities are intentionally rejected by the normal
        # closed-enum validation below.
        if isinstance(values, dict) and "backend" not in values:
            values = {"backend": DEFAULT_DISCOVERY_LAUNCH_PREFERENCES["backend"], **values}
        try:
            self._values = _validate_shape_and_values(values)
        except DiscoveryPreferencesValidationError:
            # A damaged or stale developer-owned file must not make the sidecar unusable.
            # The installed defaults are authoritative until a valid save replaces it.
            self._values = copy.deepcopy(DEFAULT_DISCOVERY_LAUNCH_PREFERENCES)

    def get(self) -> dict[str, Any]:
        return copy.deepcopy(self._values)

    def snapshot(self) -> dict[str, Any]:
        """Return the immutable-by-convention values copied into a new Launch."""
        values = self.get()
        # ``launch_discovery.py`` deliberately collapses a skipped idea-generation
        # execution to one round.  Record that effective value in the Launch snapshot
        # so the persisted configuration describes what the runner will actually do.
        if values["skip_idea_generation"]:
            values["workflow"]["loop_rounds"] = 1
        return values

    def save(self, proposed: Mapping[str, Any]) -> dict[str, Any]:
        """Validate and atomically replace the complete defaults document.

        The endpoint accepts either the complete values object or a ``values`` wrapper.
        A wrapper is useful for the settings document; omitted fields are filled from the
        current defaults, but every supplied field is still validated and unknown fields
        are rejected.  The ranking criteria object remains all-or-nothing.
        """
        if not isinstance(proposed, Mapping):
            raise DiscoveryPreferencesValidationError(
                "Discovery Launch preferences must be an object",
                [_violation("", "an object is required")],
            )
        wrapper_unknown = set(proposed) - {
            "values",
            "schema_version",
            "defaults",
            "parameters",
        }
        if "values" in proposed:
            wrapper_violations = [
                _violation(key, "unknown settings document field")
                for key in sorted(wrapper_unknown)
            ]
            if wrapper_violations:
                raise DiscoveryPreferencesValidationError(
                    "Discovery Launch preferences contain unknown fields",
                    wrapper_violations,
                )
            supplied_version = proposed.get("schema_version")
            if supplied_version is not None and supplied_version != self.schema_version:
                raise DiscoveryPreferencesValidationError(
                    "Discovery Launch preferences use an unsupported schema version",
                    [_violation("schema_version", "must match the installed schema version")],
                )
        candidate_payload: Any = proposed.get("values", proposed)
        if not isinstance(candidate_payload, Mapping):
            raise DiscoveryPreferencesValidationError(
                "Discovery Launch preferences values must be an object",
                [_violation("values", "an object is required")],
            )
        unknown_top = set(candidate_payload) - set(_EXPECTED_SHAPE)
        for key in sorted(unknown_top):
            # Validate the full candidate below so callers receive all violations at once.
            pass
        candidate = copy.deepcopy(self._values)
        _deep_merge(candidate, candidate_payload)
        normalized = _validate_shape_and_values(candidate)
        self._atomic_write(normalized)
        self._values = normalized
        return self.document()

    def document(self) -> dict[str, Any]:
        values = self.get()
        defaults = copy.deepcopy(DEFAULT_DISCOVERY_LAUNCH_PREFERENCES)
        parameters = copy.deepcopy(_PARAMETER_DEFINITIONS)
        return {
            "schema_version": self.schema_version,
            "values": values,
            "defaults": defaults,
            "parameters": parameters,
        }

    def _atomic_write(self, values: dict[str, Any]) -> None:
        self.path.parent.mkdir(parents=True, exist_ok=True)
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{self.path.name}.", suffix=".tmp", dir=self.path.parent
        )
        temporary_path = Path(temporary_name)
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
                json.dump(
                    {"schema_version": self.schema_version, "values": values},
                    handle,
                    ensure_ascii=False,
                    indent=2,
                    sort_keys=True,
                )
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_path, self.path)
        finally:
            temporary_path.unlink(missing_ok=True)


def _deep_merge(target: dict[str, Any], patch: Mapping[str, Any]) -> None:
    """Merge a settings patch while retaining omitted sibling defaults."""
    for key, value in patch.items():
        if isinstance(value, Mapping) and isinstance(target.get(key), dict):
            _deep_merge(target[key], value)
        else:
            target[key] = copy.deepcopy(value)


def discovery_preferences_document(path: str | Path) -> dict[str, Any]:
    """Convenience adapter for callers that only have a storage path."""
    return DiscoveryLaunchPreferences(path).document()


__all__ = [
    "DEFAULT_DISCOVERY_LAUNCH_PREFERENCES",
    "DiscoveryLaunchPreferences",
    "DiscoveryPreferencesValidationError",
    "discovery_preferences_document",
]
