"""
MCTS Node for Vegapunk
Define the node structure for Aider MCTS search
"""

import math
import os
import time
import uuid
import threading
from typing import Optional, List, Dict, Any, Set, Literal, Union
from dataclasses import dataclass, field
from functools import total_ordering

import numpy as np
from dataclasses_json import DataClassJsonMixin


@dataclass
@total_ordering
class MetricValue(DataClassJsonMixin):  # gt returns T or F, T means better than the other
    """
    Represents the value of a metric to be optimized, which can be compared to other metric values.
    Comparisons (and max, min) are based on which value is better, not which is larger.
    """

    value: float | int | np.number | np.floating | np.ndarray | None
    maximize: bool | None = field(default=None, kw_only=True)

    def __post_init__(self):
        if self.value is not None:
            assert isinstance(self.value, (float, int, np.number, np.floating))
            self.value = float(self.value)

    def __gt__(self, other) -> bool:
        """True if self is a _better_ (not necessarily larger) metric value than other"""
        if self.value is None:
            return False
        if other.value is None:
            return True

        assert type(self) is type(other) and (
            self.maximize == other.maximize
        ), "Cannot compare different metrics"

        if self.value == other.value:
            return False

        comp = self.value > other.value
        return comp if self.maximize else not comp  # type: ignore

    def __eq__(self, other: Any) -> bool:
        return self.value == other.value

    def __repr__(self) -> str:
        return str(self)

    def __str__(self) -> str:
        if self.maximize is None:
            opt_dir = "?"
        elif self.maximize:
            opt_dir = "↑"
        else:
            opt_dir = "↓"
        return f"Metric{opt_dir}({self.value_npsafe:.4f})"

    @property
    def is_worst(self):
        """True if the metric value is the worst possible value."""
        return self.value is None

    @property
    def value_npsafe(self):
        return self.value if self.value is not None else float("nan")


@dataclass
class WorstMetricValue(MetricValue):
    """
    Represents an invalid metric value, e.g. when the agent creates a buggy solution.
    Always compares worse than any valid metric value.
    """

    value: None = None

    def __repr__(self):
        return super().__repr__()

    def __str__(self):
        return super().__str__()


@dataclass(eq=False)
class AiderMCTSNode:
    """Aider MCTS Node - Represents a complete code solution"""
    
    # Basic attributes
    run_number: Optional[Union[str, int]] = None  # Supports string (e.g. "run_1_1") and integer
    parent: Optional['AiderMCTSNode'] = None
    workspace_folder: Optional[str] = None  # Independent workspace path for the node
    
    # Execution state
    is_buggy: Optional[bool] = None
    metric: Optional[MetricValue] = None  # Changed to MetricValue type (aligned with base_mcts)
    results: Dict[str, Any] = field(default_factory=dict)
    
    # MCTS statistics
    visits: int = 0
    total_reward: float = 0.0
    
    # Tree structure
    children: Set['AiderMCTSNode'] = field(default_factory=set)
    
    # Metadata (aligned with base_mcts)
    id: str = field(default_factory=lambda: uuid.uuid4().hex)
    created_time: float = field(default_factory=time.time)
    
    # Execution related
    exec_result: Optional[Dict[str, Any]] = None
    error_info: Optional[Dict[str, Any]] = None
    
    # MCTS related attributes (aligned with base_mcts)
    is_terminal: bool = False
    is_debug_success: bool = False
    continue_improve: bool = False
    stage: Literal["root", "improve", "debug", "draft"] = "draft"  # Aligned with base_mcts
    lock: bool = False
    expected_child_count: int = 0
    step: int = 0
    child_count_lock: threading.Lock = field(default_factory=threading.Lock)
    
    # Aligned with base_mcts: depth and failure count
    debug_depth: int = 0
    improve_failure_depth: int = 0
    
    # Aligned with base_mcts: local_best_node for tracking the best node within a branch
    local_best_node: Optional['AiderMCTSNode'] = None
    
    def __post_init__(self):
        # ID and timestamp are now auto-generated by field(default_factory) (aligned with base_mcts)
        
        # Aligned with base_mcts: automatically handle parent-child relationships
        if self.parent is not None:
            self.parent.children.add(self)
    
    def __hash__(self):
        """Make node hashable for set storage (aligned with base_mcts)"""
        return hash(self.id)
    
    def __eq__(self, other):
        """Node equality comparison (aligned with base_mcts)"""
        if not isinstance(other, AiderMCTSNode):
            return False
        return self.id == other.id
    
    def add_child(self, child: 'AiderMCTSNode'):
        """Add a child node"""
        child.parent = self
        self.children.add(child)
    
    def uct_value(self, exploration_constant: float = 1.414) -> float:
        """Calculate UCT value"""
        if self.visits == 0:
            return float('inf')  # Prioritize unvisited nodes
        
        parent_visits = self.parent.visits if self.parent else 0
        exploitation = self.total_reward / self.visits
        exploration = exploration_constant * (math.log(parent_visits + 1) / (self.visits + 1e-8)) ** 0.5
        
        return exploitation + exploration
    
    def update(self, result: float, add: bool = True):
        """Update node reward - aligned with base_mcts update method"""
        if add:
            self.visits += 1
            self.total_reward += result
    
    def update_reward(self, reward: float):
        """Update node reward (backward-compatible alias)"""
        self.update(reward, add=True)
    
    def get_debug_depth(self) -> int:
        """Calculate debug depth - aligned with base_mcts logic"""
        if self.stage != "debug":
            return 0
        if self.parent is None:
            return 1
        return self.parent.get_debug_depth() + 1
    
    def get_experiment_file(self) -> Optional[str]:
        """Get the experiment.py file path for this node"""
        if self.workspace_folder:
            return os.path.join(self.workspace_folder, "experiment.py")
        return None
    
    def read_code(self) -> str:
        """Read code on demand (if truly needed)"""
        exp_file = self.get_experiment_file()
        if exp_file and os.path.exists(exp_file):
            with open(exp_file, 'r') as f:
                return f.read()
        return ""
    
    
    def is_fully_expanded(self, scfg=None) -> bool:
        """Check if fully expanded - aligned with base_mcts"""
        if scfg is None:
            return len(self.children) > 0
        
        if self.stage == "root":
            # Root node: check if max draft count is reached
            return len(self.children) >= scfg.num_drafts
        else:
            if self.is_buggy:
                # Buggy node: fully expanded if it has a non-buggy child
                if self.has_no_bug_child():
                    return True
                else:
                    return len(self.children) >= scfg.num_bugs
            else:
                # Normal node: check if max improve count is reached
                return len(self.children) >= scfg.num_improves
    
    def is_fully_expanded_with_expected(self, scfg=None) -> bool:
        """Check if fully expanded (including expected children) - aligned with base_mcts"""
        if scfg is None:
            return len(self.children) > 0
            
        if self.stage == "root":
            return self.expected_child_count >= scfg.num_drafts
        else:
            if self.is_buggy:
                if self.has_no_bug_child():
                    return True
                else:
                    return self.expected_child_count >= scfg.num_bugs
            else:
                return self.expected_child_count >= scfg.num_improves
    
    def has_no_bug_child(self) -> bool:
        """Check if there is a non-buggy child node"""
        for child in self.children:
            if not child.is_buggy:
                return True
        return False
    
    def add_expected_child_count(self):
        """Increment expected child count - aligned with base_mcts"""
        with self.child_count_lock:
            self.expected_child_count += 1
            print(f"Node {self.id} expected_child_count increased to {self.expected_child_count}")
            
    def sub_expected_child_count(self):
        """Decrement expected child count - aligned with base_mcts"""
        with self.child_count_lock:
            self.expected_child_count -= 1
            print(f"Node {self.id} expected_child_count decreased to {self.expected_child_count}")
    
    def __str__(self) -> str:
        """String representation"""
        return f"AiderMCTSNode(id={self.id}, run_number={self.run_number}, " \
               f"is_buggy={self.is_buggy}, metric={self.metric}, " \
               f"visits={self.visits}, reward={self.total_reward:.3f})"
    
    def __repr__(self) -> str:
        """Detailed string representation"""
        return self.__str__()


# Test function
def test_mcts_node():
    """Test MCTS Node"""
    print("Testing MCTS Node...")
    
    # Create test nodes (using workspace_folder instead of code)
    root = AiderMCTSNode(run_number=0, workspace_folder="test_workspace_root")
    child1 = AiderMCTSNode(run_number=1, parent=root, workspace_folder="test_workspace_1")
    child2 = AiderMCTSNode(run_number=2, parent=root, workspace_folder="test_workspace_2")
    
    # Test basic functionality
    print(f"Root: {root}")
    print(f"Child1: {child1}")
    print(f"Child2: {child2}")
    
    # Test UCT calculation
    print(f"Root UCT: {root.uct_value()}")
    print(f"Child1 UCT: {child1.uct_value()}")
    print(f"Child2 UCT: {child2.uct_value()}")
    
    # Test reward update
    child1.update_reward(0.8)
    child2.update_reward(0.6)
    
    print(f"After rewards - Child1: visits={child1.visits}, reward={child1.total_reward}")
    print(f"After rewards - Child2: visits={child2.visits}, reward={child2.total_reward}")
    
    # Test tree structure functionality
    print(f"Root children count: {len(root.children)}")
    print(f"Child1 children count: {len(child1.children)}")
    
    print("MCTS Node test completed!")


if __name__ == "__main__":
    test_mcts_node()